---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: ${snapshot_name}
  labels:
    test.appstudio.openshift.io/type: component
    appstudio.openshift.io/component: ${component_name}
    pac.test.appstudio.openshift.io/event-type: push
    originating-tool: "${originating_tool}"
spec:
  application: ${application_name}
  components:
    - name: ${component_name}
      containerImage: ${sample_image}
      source:
        git:
          url: ${git_source_url}
          revision: ${git_source_revision}
