---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-pyxis-image
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task that pushes metadata to Pyxis for all container images contained in a snapshot that is the
    result of the `apply-mapping` task. It first extracts the containerImages from the snapshot, then runs
    `skopeo inspect` on each, before finally pushing metadata to Pyxis.

    The task includes protection against race conditions that could occur when multiple components have the same
    digest. Components with the same digest are processed in series while different digest groups are processed
    in parallel, ensuring optimal performance while preventing conflicts.

    The relative path of the pyxis.json file in the data workspace is output as a task result named
    `pyxisDataPath`.
  params:
    - name: server
      type: string
      description: The server type to use. Options are 'production','production-internal,'stage-internal' and 'stage'
      default: production
    - name: concurrentLimit
      type: string
      description: The maximum number of components to be processed at once
      default: "16"
    - name: pyxisSecret
      type: string
      description: |
        The kubernetes secret to use to authenticate to Pyxis. It needs to contain two keys: key and cert
    - name: certified
      type: string
      description: If set to true, the images will be marked as certified in their Pyxis entries
      default: "false"
    - name: isLatest
      type: string
      description: If set to true, the images will have a latest tag added with their Pyxis entries
      default: "false"
    - name: rhPush
      type: string
      description: >
        If set to true, the entry created in ContainerImage.repositories will have its
        registry and repository fields converted to use Red Hat's official registry.
        E.g. a mapped repository of "quay.io/redhat-pending/product---my-image" will be converted
        to use registry "registry.access.redhat.com" and repository "product/my-image" and
        "quay.io/rh-flatpaks-prod/foo----bar" will be converted to "flatpaks.registry.redhat.io" and
        "foo/bar". Also, this repository entry will be marked as published
      default: "false"
    - name: processHelmCharts
      type: string
      description: >
        When true, Helm OCI artifacts are sent to Pyxis; when false (default), Helm charts are skipped
      default: "false"
    - name: snapshotPath
      type: string
      description: Path to the JSON string of the mapped Snapshot spec in the data workspace
    - name: dataPath
      description: Path to the JSON string of the merged data to use in the data workspace
      type: string
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored
      type: string
      default: "empty"
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire
      type: string
      default: "1d"
    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable
      type: string
      default: ""
    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""
    - name: sourceDataArtifact
      type: string
      description: Location of trusted artifacts to be used to populate data directory
      default: ""
    - name: dataDir
      description: The location where data will be stored
      type: string
      default: /var/workdir/release
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks and stepactions to be used are stored
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: pyxisDataPath
      description: The relative path in the workspace to the stored pyxis data json
    - description: Produced trusted data artifact
      name: sourceDataArtifact
      type: string
  volumes:
    - name: workdir
      emptyDir: {}
    - name: pyxis-secret-vol
      secret:
        secretName: $(params.pyxisSecret)
        defaultMode: 0444
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true

  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"
    securityContext:
      runAsUser: 1001
  steps:
    - name: use-trusted-artifact
      computeResources:
        limits:
          memory: 64Mi
        requests:
          memory: 64Mi
          cpu: 30m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)
    - name: create-pyxis-image
      image: quay.io/konflux-ci/release-service-utils@sha256:436b54bee56d4cee1a1c635784f6b0fcb676399f974fecfbb1506d25bace4b40
      computeResources:
        limits:
          memory: 3584Mi
        requests:
          memory: 3584Mi
          cpu: 1200m
      volumeMounts:
        - name: pyxis-secret-vol
          mountPath: "/etc/secrets"
      command: ["python3", "-m", "create_pyxis_image"]
      args:
        - --server
        - $(params.server)
        - --snapshot-file
        - $(params.dataDir)/$(params.snapshotPath)
        - --data-file
        - $(params.dataDir)/$(params.dataPath)
        - --pyxis-secret-path
        - /etc/secrets
        - --certified
        - $(params.certified)
        - --is-latest
        - $(params.isLatest)
        - --rh-push
        - $(params.rhPush)
        - --process-helm-charts
        - $(params.processHelmCharts)
        - --concurrent-limit
        - $(params.concurrentLimit)
        - --pyxis-data-path-result
        - $(results.pyxisDataPath.path)
        - --data-dir
        - $(params.dataDir)
        - --snapshot-path-relative
        - $(params.snapshotPath)
    - name: create-trusted-artifact
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 250m
      ref:
        resolver: "git"
        params:
          - name: url
            value: "$(params.taskGitUrl)"
          - name: revision
            value: "$(params.taskGitRevision)"
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
