---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: apply-mapping-run-empty-params
spec:
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: main
      - name: pathInRepo
        value: catalog/task/apply-mapping/0.6/apply-mapping.yaml
