---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-workspace
  labels:
    app.kubernetes.io/version: "0.5.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to delete a given directory in a passed workspace
  params:
    - name: subdirectory
      type: string
      description: The directory to remove within the workspace
    - name: delay
      type: string
      default: 60
      description: Time in seconds to delay the cleanup action
  workspaces:
    - name: input
      description: Workspace where the directory to cleanup exists
  steps:
    - name: cleanup
      image: quay.io/redhat-appstudio/release-service-utils:447ea0580a2cdd48b4091e1df86fab5c3f86d01c
      script: |
        #!/usr/bin/env sh
        set -eux

        if [ -z "$(params.subdirectory)" ] ; then
            echo "The empty string is not a valid subdirectory"
            exit 0
        fi

        echo "Delaying execution by $(params.delay) seconds"
        sleep $(params.delay)

        CLEANUP_DIR="$(workspaces.input.path)/$(params.subdirectory)"

        if [ -d "${CLEANUP_DIR}" ] ; then
          # Delete a directory and its contents
          rm -rf "${CLEANUP_DIR}"/
        fi
