---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: validate-enterprise-contract
spec:
  params:
    - name: applicationSnapshot
      type: string
      description: JSON representation of the ApplicationSnapshot being released
      default: ""
    - name: policy
      type: string
      description: Name of the policy to apply when validating the enterprise contract
      default: ""
    - name: shouldFail
      type: string
      description: Whether the validation should fail or not
      default: "false"
  steps:
    - name: fake-ec-validation
      image: quay.io/hacbs-release/release-utils
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "$(params.shouldFail)" = "true" ]; then
          exit 1
        fi
