---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: "${snapshot_name}"
  namespace: "${tenant_namespace}"
  labels:
    appstudio.openshift.io/application: "${application_name}"
spec:
  application: "${application_name}"
  artifacts: {}
  components:
    - name: "${component_name}"
      containerImage: "${container_image}"
