---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: extract-index-image
  labels:
    app.kubernetes.io/version: "0.3.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
      Extract the index image fields from the inputDataFile
  params:
    - name: inputDataFile
      type: string
  workspaces:
    - name: data
      description: Workspace where the inputDataFile is stored
  results:
    - name: indexImage
      type: string
    - name: indexImageResolved
      type: string
  steps:
    - name: extract-index-image
      image: >-
        quay.io/redhat-appstudio/release-service-utils:447ea0580a2cdd48b4091e1df86fab5c3f86d01c
      script: |
        #!/usr/bin/env sh
        set -ex

        jsonBuildInfo=`jq -cr .jsonBuildInfo $(params.inputDataFile)`

        indexImage=`echo $jsonBuildInfo | jq -cr .index_image`
        echo -n $indexImage > $(results.indexImage.path)

        indexImageResolved=`echo $jsonBuildInfo | jq -cr .index_image_resolved`
        echo -n $indexImageResolved > $(results.indexImageResolved.path)
