---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: extract-index-image
  labels:
    app.kubernetes.io/version: "0.2.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
      Extract the index image fields from the inputDataFile
  params:
    - name: inputDataFile
      type: string
  workspaces:
    - name: input
      description: Workspace where the inputDataFile is stored
  results:
    - name: indexImage
      type: string
    - name: indexImageResolved
      type: string
  steps:
    - name: extract-index-image
      image: >-
        quay.io/hacbs-release/release-utils@sha256:5733ece907aa70d6ebced36484c936731e8b27bfcf87fed226a0ecf95047a6b8
      script: |
        #!/usr/bin/env sh
        set -ex

        jsonBuildInfo=`jq -cr .jsonBuildInfo $(params.inputDataFile)`

        indexImage=`echo $jsonBuildInfo | jq -cr .index_image`
        echo $indexImage > $(results.indexImage.path)

        indexImageResolved=`echo $jsonBuildInfo | jq -cr .index_image_resolved`
        echo $indexImageResolved > $(results.indexImageResolved.path)
