---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: extract-index-image
  labels:
    app.kubernetes.io/version: "1.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
      Extract the index image fields from the inputDataFile
  params:
    - name: inputDataFile
      type: string
    - name: resultsDirPath
      type: string
      description: Path to the results directory in the data workspace
  workspaces:
    - name: data
      description: Workspace where the inputDataFile is stored
  results:
    - name: indexImage
      type: string
    - name: indexImageResolved
      type: string
  steps:
    - name: extract-index-image
      image: >-
        quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env sh
        set -ex

        RESULTS_FILE="$(workspaces.data.path)/$(params.resultsDirPath)/extract-index-image-results.json"

        jsonBuildInfo=`jq -cr .jsonBuildInfo $(params.inputDataFile)`

        indexImage=`echo $jsonBuildInfo | jq -cr .index_image`
        echo -n $indexImage > $(results.indexImage.path)

        indexImageResolved=`echo $jsonBuildInfo | jq -cr .index_image_resolved`
        echo -n $indexImageResolved > $(results.indexImageResolved.path)

        jq -n --arg image "$indexImage" --arg resolved "$indexImageResolved" \
          '{"index_image": {"index_image": $image, "index_image_resolved": $resolved}}' | tee $RESULTS_FILE
