---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: base64-encode-checksum
  labels:
    app.kubernetes.io/version: "1.2.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Task to encode the Terraform Checksum file
  params:
    - name: binaries_dir
      type: string
      description: Path where the binaries are stored in the workspace
      default: "binaries"
  workspaces:
    - name: data
      description: The workspace where the snapshot is stored. The extracted binaries will be stored here as well.
  results:
    - name: blob
      type: string
      description: blob to sign, that is the result of the base64 encoded checksum
  steps:
    - name: base64-encode-checksum
      image:
        quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env sh
        set -ex

        FILE_PATH="$(workspaces.data.path)/$(params.binaries_dir)"
        base64 -w 0 "$FILE_PATH"/*SHA256SUMS | tee "$(results.blob.path)"
