---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: collect-data-run
spec:
  params:
    - name: release
      value: "default/release"
    - name: releasePlan
      value: "default/release-plan"
    - name: releasePlanAdmission
      value: "default/release-plan-admission"
    - name: releaseStrategy
      value: "default/release-strategy"
    - name: snapshot
      value: "default/snapshot"
  taskRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/task-collect-data:0.1
      - name: kind
        value: task
      - name: name
        value: collect-data
