#!/usr/bin/env bash
# Mock get-image-architectures returning two architectures amd64 and s390x
echo '{"platform":{"architecture": "amd64", "os": "linux"}, "digest": "sha256:abcdefg"}'
echo '{"platform":{"architecture": "s390x", "os": "linux"}, "digest": "sha256:deadbeef"}'
