---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: use-trusted-artifact-array
spec:
  description: >-
    This stepaction extracts an array of Trusted Artifacts into a folder.
  image: quay.io/konflux-ci/build-trusted-artifacts:8b09217702ec665d4fae6d09f6a7910421f15b69
  env:
    # Set HOME variable to something else than `/` to avoid 'permission denied' problems when writing files.
    - name: HOME
      value: /tekton/home
    - name: CA_FILE
      value: $(params.caCertPath)
  params:
    - name: sourceDataArtifacts
      type: array
      description: Array of artifacts to extract
      default: []
    - name: caCertPath
      type: string
      default: "/mnt/trusted-ca/ca-bundle.crt"
      description: Path to CA certificate bundle for TLS verification with self-signed certificates
  args:
    - use
    - "$(params.sourceDataArtifacts[*])"
