title = "Gitleaks Config"

[extend]
useDefault = false  # Keeps the standard Gitleaks rules active

[[rules]]
    # we handle sensitive data by mounting secrets to volumes and loading them into environment variables via the cat command.
    # If shell tracing (the set -x flag) is enabled, these secrets are leaked into the task logs
    # This rule is to check the above situation and ignore the false positives.
    id = "bash-set-x-cat-secrets"
    regex = '''(?ims)^[ \t]*set\s+-[^#\n]*x.*?(?:=)["']?\s*(?:\$\(|\`)?\s*(?:cat\s+)?["']?(?:/etc/secrets|/mnt/)'''
    # regex = '''(?ims)^[ \t]*set\s+-[^#\n]*x.*?(?:=|cat\s+)[^ \n]*?["']?(?:/etc/secrets|/mnt/)'''
    keywords = ["set", "cat", "/etc/secrets", "/mnt"]
    [rules.allowlist]
        regexes = [
            # If a Shebang (#!) appears between set -x and cat, the debug mode has been 'reset' by the new shell. 
            '''(?is)set\s+-[^ \n]*x.*?#!/.*?cat\s+''',
            # This rule is to ensure that no closing curly brace } appears but no opening brace '{' between set -x and cat.
            '''(?is)set\s+-[^ \n]*x[^{]*?}.*?cat\s+''',
            # This rule ignores the situation that 'set +x' (or a variant) is detected between the 
            # initial 'set -x' and the sensitive path access.          
            '''(?is)set\s+-[^ \n]*x.*?[ \t]*set\s+\+[^ \n]*x.*?(?:/etc/secrets|/mnt/)'''
        ]
        paths = [
        #         '''tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml'''
        ]
    severity = "high"
