---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant_namespace}

resources:
  - ../../../shared/resources/tenant
  - sa.yaml
  - sa-rolebinding.yaml
  - secrets/tenant-secrets.yaml

patches:
  - path: rp.yaml
