---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: fbc-release-run-empty-params
spec:
  params:
    - name: snapshot
      value: ""
    - name: enterpriseContractPolicy
      value: ""
    - name: fromIndex
      value: ""
    - name: overwriteFromIndex
      value: ""
    - name: binaryImage
      value: ""
    - name: buildTags
      value: ""
    - name: addArches
      value: ""
    - name: requestUpdateTimeout
      value: ""
    - name: buildTimeoutSeconds
      value: ""
  pipelineRef:
    name: fbc-release
    bundle: quay.io/hacbs-release/pipeline-fbc-release:0.4
