#!/usr/bin/env bash
set -eo pipefail

if [[ "$1" == "create" ]]; then
  cat > /dev/null
  echo '{"apiVersion":"appstudio.redhat.com/v1alpha1","kind":"InternalRequest","metadata":{"name":"push-disk-images-ir","namespace":"default"}}'
elif [[ "$1" == "get" && "$2" == "internalrequest" ]]; then
  if [[ "$*" == *"-l"* ]]; then
    echo '{"items":[]}'
  elif [[ "$*" == *"jsonpath"* ]]; then
    echo '{"result":"Success"}'
  else
    echo '{"apiVersion":"appstudio.redhat.com/v1alpha1","kind":"InternalRequest","metadata":{"name":"push-disk-images-ir","namespace":"default"},"status":{"conditions":[{"reason":"Succeeded","status":"True","type":"Succeeded"}],"results":{"result":"Success"},"pipelineRun":"test-run"}}'
  fi
elif [[ "$1" == "delete" ]]; then
  echo "deleted"
else
  echo '{"result":"Success"}'
fi
