---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: check-fbc-opt-in
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Simple task to check FBC opt-in status in Pyxis for container images.
    Returns opt-in status for each provided container image.
  params:
    - name: containerImages
      description: JSON array of container images to check for FBC opt-in status
      type: string
    - name: iibServiceAccountSecret
      description: Secret with IIB service account credentials to be used for Pyxis authentication
      type: string
    - name: pyxisUrl
      description: Pyxis url to use
      type: string
    - name: pyxisServer
      description: Pyxis server to use
      type: string
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: optInResults
      type: string
      description: |-
        JSON array containing opt-in status for each container image.

        Schema:
        [
          {
            "containerImage": "registry.io/image:tag",
            "fbcOptIn": boolean
          }
        ]
  volumes:
    - name: workdir
      emptyDir: {}
    - name: service-account-secret
      secret:
        secretName: $(params.iibServiceAccountSecret)
        defaultMode: 0444
    - name: iib-services-config-vol
      secret:
        secretName: iib-services-config
        defaultMode: 0444
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    securityContext:
      runAsUser: 1001
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      - name: service-account-secret
        mountPath: /mnt/service-account-secret
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
  steps:
    - name: check-opt-in
      image: quay.io/konflux-ci/release-service-utils@sha256:6979552f11f042b8730abcb1be4ec6cfb0553a069cc352643f88d8996041abf8
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 200m
      volumeMounts:
        - name: iib-services-config-vol
          mountPath: /mnt/iib-services-config
      env:
        - name: PYXIS_URL
          value: $(params.pyxisUrl)
        - name: PYXIS_SERVER
          value: $(params.pyxisServer)
        - name: CONTAINER_IMAGES
          value: $(params.containerImages)
        - name: RESULT_OPT_IN_RESULTS
          value: $(results.optInResults.path)
      command: ["/home/scripts/python/tasks/internal/check_fbc_opt_in.py"]
