---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-workspace
spec:
  params:
    - name: subdirectory
      type: string
      description: The directory to remove within the workspace
  workspaces:
    - name: input
      description: Workspace where the directory to cleanup exists
  steps:
    - name: cleanup
      image: quay.io/hacbs-release/release-utils
      script: |
        #!/usr/bin/env sh
        set -eux

        if [ -z "$(params.subdirectory)" ] ; then
            echo "The empty string is not a valid subdirectory"
            exit 0
        fi

        CLEANUP_DIR="$(workspaces.input.path)/$(params.subdirectory)"

        if [ -d "${CLEANUP_DIR}" ] ; then
          # Delete a directory and its contents
          rm -rf "${CLEANUP_DIR}"/
        fi
