#!/usr/bin/env bash
# Tekton test mock: default SA cannot read configmaps in unit tests.
set -eux
if [[ "$*" == "get configmap create-advisory-test-cm -o jsonpath={.data.SIG_KEY_NAME}" ]]; then
  echo key1
else
  exec /usr/bin/kubectl "$@"
fi
