---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: collect-pyxis-params
  labels:
    app.kubernetes.io/version: "0.5.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task that collects pyxis configuration options from the data file
  params:
    - name: dataPath
      type: string
      description: Path to the JSON string of the merged data containing the pyxis configuration options to use
  workspaces:
    - name: data
      description: The workspace where the snapshot spec json file resides
  results:
    - name: server
      type: string
      description: |
        The server type to use. Options are 'production','production-internal,'stage-internal' and 'stage'.
        Default is 'production'
    - name: secret
      type: string
      description: |
        The kubernetes secret to use to authenticate to Pyxis. It needs to contain two keys: key and cert
  steps:
    - name: collect-pyxis-params
      image:
        quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -x

        DATA_FILE="$(workspaces.data.path)/$(params.dataPath)"
        if [ ! -f "${DATA_FILE}" ] ; then
            echo "No valid data file was provided."
            exit 1
        fi

        if [ "$(jq '.pyxis | has("secret")' "$DATA_FILE")" == false ] ; then
            echo "Pyxis key or secret missing in data JSON file"
            exit 1
        fi
        jq -jr '.pyxis.secret' "$DATA_FILE" > "$(results.secret.path)"
        jq -jr '.pyxis.server // "production"' "$DATA_FILE" > "$(results.server.path)"
