---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: slack-webhook-notification-run-empty-params
spec:
  params:
    - name: message
      value: ""
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: main
      - name: pathInRepo
        value: catalog/task/slack-webhook-notification/0.1/slack-webhook-notification.yaml
