---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  data:
    intention: staging
    cdn:
      env: stage
    jira:
      jiraSecret: advisory-jira-secret-${component_name}
    sign:
      configMapName: "hacbs-signing-pipeline-config-staging-e2e"
      cosignSecretName: "konflux-cosign-signing-stage-${component_name}"
    releaseNotes:
      product_id:
        - 10681
      product_name: Konflux Release E2E Test Product
      product_version: '1.0'
      cpe: 'cpe:/a:redhat:comp2:1::appstream'
      product_stream: comp2-1.0
    mapping:
      defaults:
        tags:
          - latest
        pushSourceContainer: true
      components:
        - name: ${component_name}
          files:
            - filename: releng-test-product-binaries-windows-amd64.tar.gz 
              source: /releases/releng-test-product-binaries-windows-amd64.tar.gz
              delivery_format: 
                - compressed
                - raw
              arch: amd64
              os: windows
            - filename: releng-test-product-binaries-linux-amd64.tar.gz
              source: /releases/releng-test-product-binaries-linux-amd64.tar.gz
              arch: amd64
              os: linux
            - filename: releng-test-product-binaries-darwin-amd64.tar.gz
              source: /releases/releng-test-product-binaries-darwin-amd64.tar.gz
              arch: amd64
              os: darwin
            - filename: releng-test-product-binaries-linux-arm64.tar.gz
              source: /releases/releng-test-product-binaries-linux-arm64.tar.gz
              delivery_format: 
                - compressed
              arch: arm64
              os: linux
            - filename: releng-test-product-binaries-darwin-arm64.tar.gz
              source: /releases/releng-test-product-binaries-darwin-arm64.tar.gz
              arch: arm64
              os: darwin
          contentGateway:
            productName: "Konflux Release E2E test product"
            productCode: "RelengTestProduct"
            productVersionName: "1.6.0"
            contentType: "binary"
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/push-artifacts-to-cdn/push-artifacts-to-cdn.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
