#!/usr/bin/env sh

echo Mock cosign called with: $*
echo $* >> ${WORKSPACE_DIR}/mock_cosign.txt

if [[ "$*" != "download sbom --output-file myImageID"[12]".json imageurl"[12] ]]
then
    echo Error: Unexpected call
    exit 1
fi

touch /workdir/sboms/${4}
