#!/usr/bin/env sh

echo Mock upload_sbom called with: $*
echo $* >> ${WORKSPACE_DIR}/mock_upload_sbom.txt

if [[ "$*" != "--retry --sbom-path "*".json" ]]
then
    echo Error: Unexpected call
    exit 1
fi
