---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: cleanup-workspace-run-empty-params
spec:
  params:
    - name: subdirectory
      value: ""
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: legacy
      - name: pathInRepo
        value: catalog/task/cleanup-workspace/0.2/cleanup-workspace.yaml
