---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: cleanup-workspace-run-empty-params
spec:
  params:
    - name: subdirectory
      value: ""
  taskRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/task-cleanup-workspace:0.2
      - name: kind
        value: task
      - name: name
        value: cleanup-workspace
