---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "release"
  name: slack-webhook-notification
spec:
  description: >-
    Sends message to slack using incoming webhook
  params:
    - name: message
      description: Message to be sent
    - name: extraDataJsonPath
      description: path to extraData json file
      default: "$(workspaces.data.path)/extra_data.json"
    - name: secretName
      description: |
        Name of secret which contains key/value pairs of `<team>/<webhook url>`. 
        e.g. team1=https://hooks.slack.com/services/XXX/XXXXXX
      default: slack-webhook-notification-secret
  volumes:
    - name: webhook-secret
      secret:
        secretName: $(params.secretName)
  steps:
    - name: send-message
      image: >-
        quay.io/hacbs-release/release-utils@sha256:5733ece907aa70d6ebced36484c936731e8b27bfcf87fed226a0ecf95047a6b8
      volumeMounts:
        - name: webhook-secret
          mountPath: "/etc/secrets"
          readOnly: true
      env:
        - name: HOME
          value: /tekton/home
        - name: MESSAGE
          value: $(params.message)
      script: |
        #!/usr/bin/env bash

        # get keyName from ExtraData
        echo "extraData location : $(params.extraDataJsonPath)"
        echo "extraData content  :"
        cat "$(params.extraDataJsonPath)"
        echo ""
        # See https://stackoverflow.com/a/56205949 to handle empty value or missing field
        keyName=$(cat "$(params.extraDataJsonPath)" | jq -r '."slack-webhook-notification-secret-keyname" // empty')
        echo "keyName: ${keyName}"

        if [ "${keyName}" == "" ] ; then
          echo "No secret key name provided via 'slack-webhook-notification-secret-keyname' key in extraData."
          echo "No message will be sent."
          exit 0
        fi

        if [ -f "/etc/secrets/$keyName" ]; then
          WEBHOOK_URL=$(cat "/etc/secrets/$keyName")
        else
          echo "Secret not defined properly"
          exit 1
        fi
        curl -X POST -H 'Content-type: application/json' --data "{\"username\": \"RHTAP Release Service\", \
          \"text\":\"$MESSAGE\"}" $WEBHOOK_URL
  workspaces:
    - name: data
      description: The workspace where the extraData json file resides
