---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: update-ocp-tag-run-empty-params
spec:
  params:
    - name: fromIndex
      value: ""
    - name: targetIndex
      value: ""
    - name: binaryImage
      value: ""
    - name: ocpVersion
      value: ""  
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: main
      - name: pathInRepo
        value: catalog/task/update-ocp-tag/0.1/update-ocp-tag.yaml
