---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: publish-index-image-run-empty-params
spec:
  params:
    - name: requestJsonResults
      value: ""
    - name: targetIndex
      value: ""
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: legacy
      - name: pathInRepo
        value: catalog/task/publish-index-image/0.3/publish-index-image.yaml
