---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  name: ${image_repository_name}
  labels:
    appstudio.redhat.com/application: ${application_name}
    appstudio.redhat.com/component: ${component_name}
    originating-tool: "${originating_tool}"
spec:
  image:
    name: ${tenant_namespace}/${application_name}/${component_image_basename}
    visibility: public
