---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: fbc-release
  labels:
    app.kubernetes.io/version: "4.0.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton release pipeline to interact with FBC Pipeline
  params:
    - name: release
      type: string
      description:
        The namespaced name (namespace/name) of the Release custom resource initiating this pipeline execution
    - name: releasePlan
      type: string
      description: The namespaced name (namespace/name) of the releasePlan
    - name: releasePlanAdmission
      type: string
      description: The namespaced name (namespace/name) of the releasePlanAdmission
    - name: releaseServiceConfig
      type: string
      description: The namespaced name (namespace/name) of the releaseServiceConfig
    - name: snapshot
      type: string
      description: The namespaced name (namespace/name) of the snapshot
    - name: enterpriseContractPolicy
      type: string
      description: JSON representation of the EnterpriseContractPolicy
    - name: enterpriseContractExtraRuleData
      type: string
      description: |
        Extra rule data to be merged into the policy specified in params.enterpriseContractPolicy. Use syntax
        "key1=value1,key2=value2..."
      default: "pipeline_intention=release"
    - name: enterpriseContractTimeout
      type: string
      description: Timeout setting for `ec validate`
      default: 40m0s
    - name: verify_ec_task_bundle
      type: string
      description: The location of the bundle containing the verify-enterprise-contract task
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/release-service-catalog.git
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
    - name: postCleanUp
      type: string
      description: Cleans up workspace after finishing executing the pipeline
      default: "true"
  workspaces:
    - name: release-workspace
  results:
    - name: requestMessage
      type: string
      value: $(tasks.add-fbc-contribution-to-index-image.results.requestMessage)
    - name: requestReason
      type: string
      value: $(tasks.add-fbc-contribution-to-index-image.results.requestReason)
    - name: iibIndexImage
      type: string
      value: $(tasks.extract-index-image.results.indexImage)
    - name: iibIndexImageResolved
      type: string
      value: $(tasks.extract-index-image.results.indexImageResolved)
  tasks:
    - name: verify-access-to-resources
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/verify-access-to-resources/verify-access-to-resources.yaml
      params:
        - name: release
          value: $(params.release)
        - name: releasePlan
          value: $(params.releasePlan)
        - name: releasePlanAdmission
          value: $(params.releasePlanAdmission)
        - name: releaseServiceConfig
          value: $(params.releaseServiceConfig)
        - name: snapshot
          value: $(params.snapshot)
        - name: requireInternalServices
          value: "true"
    - name: collect-data
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/collect-data/collect-data.yaml
      params:
        - name: release
          value: $(params.release)
        - name: releasePlan
          value: $(params.releasePlan)
        - name: releasePlanAdmission
          value: $(params.releasePlanAdmission)
        - name: releaseServiceConfig
          value: $(params.releaseServiceConfig)
        - name: snapshot
          value: $(params.snapshot)
        - name: subdirectory
          value: $(context.pipelineRun.uid)
      workspaces:
        - name: data
          workspace: release-workspace
      runAfter:
        - verify-access-to-resources
    - name: validate-single-component
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/validate-single-component/validate-single-component.yaml
      params:
        - name: snapshotPath
          value: "$(tasks.collect-data.results.snapshotSpec)"
      workspaces:
        - name: data
          workspace: release-workspace
      runAfter:
        - collect-data
    - name: verify-enterprise-contract
      taskRef:
        resolver: "bundles"
        params:
          - name: bundle
            value: $(params.verify_ec_task_bundle)
          - name: kind
            value: task
          - name: name
            value: verify-enterprise-contract
      params:
        - name: IMAGES
          value: "$(workspaces.data.path)/$(tasks.collect-data.results.snapshotSpec)"
        - name: SSL_CERT_DIR
          value: /var/run/secrets/kubernetes.io/serviceaccount
        - name: POLICY_CONFIGURATION
          value: $(params.enterpriseContractPolicy)
        - name: STRICT
          value: "1"
        - name: IGNORE_REKOR
          value: "true"
        - name: EXTRA_RULE_DATA
          value: $(params.enterpriseContractExtraRuleData)
        - name: TIMEOUT
          value: $(params.enterpriseContractTimeout)
      workspaces:
        - name: data
          workspace: release-workspace
      runAfter:
        - validate-single-component
    - name: get-ocp-version
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/get-ocp-version/get-ocp-version.yaml
      params:
        - name: fbcFragment
          value: "$(tasks.collect-data.results.fbcFragment)"
      runAfter:
        - verify-enterprise-contract
    - name: update-ocp-tag
      workspaces:
        - name: data
          workspace: release-workspace
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/update-ocp-tag/update-ocp-tag.yaml
      params:
        - name: dataPath
          value: "$(tasks.collect-data.results.data)"
        - name: ocpVersion
          value: "$(tasks.get-ocp-version.results.stored-version)"
    - name: check-fbc-packages
      workspaces:
        - name: data
          workspace: release-workspace
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/check-fbc-packages/check-fbc-packages.yaml
      params:
        - name: dataPath
          value: "$(tasks.collect-data.results.data)"
        - name: snapshotPath
          value: "$(tasks.collect-data.results.snapshotSpec)"
      runAfter:
        - verify-enterprise-contract
    - name: add-fbc-contribution-to-index-image
      workspaces:
        - name: data
          workspace: release-workspace
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/add-fbc-contribution/add-fbc-contribution.yaml
      params:
        - name: dataPath
          value: "$(tasks.collect-data.results.data)"
        - name: snapshotPath
          value: "$(tasks.collect-data.results.snapshotSpec)"
        - name: binaryImage
          value: "$(tasks.update-ocp-tag.results.updated-binaryImage)"
        - name: fromIndex
          value: "$(tasks.update-ocp-tag.results.updated-fromIndex)"
        - name: targetIndex
          value: "$(tasks.update-ocp-tag.results.updated-targetIndex)"
        - name: pipelineRunUid
          value: $(context.pipelineRun.uid)
        - name: resultsDirPath
          value: "$(tasks.collect-data.results.resultsDir)"
      runAfter:
        - check-fbc-packages
        - verify-enterprise-contract
    - name: extract-requester-from-release
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: hub/kubernetes-actions/kubernetes-actions.yaml
      params:
        - name: image
          value: "quay.io/hacbs-release/cloud-builders-kubectl\
            @sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753"
        - name: script
          value: |
            set -x

            NAMESPACE=$(echo $(params.release) | cut -d '/' -f 1)
            NAME=$(echo $(params.release) | cut -d '/' -f 2)

            AUTHOR=$(kubectl get release ${NAME} -n ${NAMESPACE} \
            -o=jsonpath='{.status.attribution.author}' | tee $(results.output-result.path))

            if [[ ${AUTHOR} == "" ]] ; then exit 1 ; fi
      runAfter:
        - verify-access-to-resources
    - name: sign-index-image
      workspaces:
        - name: data
          workspace: release-workspace
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/sign-index-image/sign-index-image.yaml
      params:
        - name: dataPath
          value: "$(tasks.collect-data.results.data)"
        - name: referenceImage
          value: $(tasks.add-fbc-contribution-to-index-image.results.requestTargetIndex)
        - name: manifestListDigests
          value: $(tasks.add-fbc-contribution-to-index-image.results.indexImageDigests)
        - name: requester
          value: $(tasks.extract-requester-from-release.results.output-result)
        - name: pipelineRunUid
          value: $(context.pipelineRun.uid)
      when:
        - input: "$(tasks.add-fbc-contribution-to-index-image.results.mustSignIndexImage)"
          operator: in
          values: ["true"]
    - name: extract-index-image
      workspaces:
        - name: data
          workspace: release-workspace
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/extract-index-image/extract-index-image.yaml
      params:
        - name: inputDataFile
          value: $(tasks.add-fbc-contribution-to-index-image.results.requestResultsFile)
        - name: resultsDirPath
          value: "$(tasks.collect-data.results.resultsDir)"
    - name: publish-index-image
      workspaces:
        - name: data
          workspace: release-workspace
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/publish-index-image/publish-index-image.yaml
      params:
        - name: dataPath
          value: "$(tasks.collect-data.results.data)"
        - name: sourceIndex
          value: $(tasks.extract-index-image.results.indexImageResolved)
        - name: targetIndex
          value: $(tasks.add-fbc-contribution-to-index-image.results.requestTargetIndex)
        - name: buildTimestamp
          value: $(tasks.add-fbc-contribution-to-index-image.results.buildTimestamp)
        - name: retries
          value: "3"
        - name: pipelineRunUid
          value: $(context.pipelineRun.uid)
      when:
        - input: $(tasks.add-fbc-contribution-to-index-image.results.mustPublishIndexImage)
          operator: in
          values: ["true"]
      runAfter:
        - sign-index-image
    - name: update-cr-status
      params:
        - name: resource
          value: $(params.release)
        - name: resultsDirPath
          value: $(tasks.collect-data.results.resultsDir)
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/update-cr-status/update-cr-status.yaml
      workspaces:
        - name: data
          workspace: release-workspace
      runAfter:
        - publish-index-image
  finally:
    - name: cleanup
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/cleanup-workspace/cleanup-workspace.yaml
      when:
        - input: $(params.postCleanUp)
          operator: in
          values: ["true"]
      params:
        - name: subdirectory
          value: "$(context.pipelineRun.uid)"
        - name: pipelineRunUid
          value: $(context.pipelineRun.uid)
      workspaces:
        - name: input
          workspace: release-workspace
