---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-advisory-severity
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |
      This task gets the advisory severity. It does this by querying OSIDB for each CVE present in the
      releaseNotesImages. For each CVE, the overall impact it is looked at. If the OSIDB entry lists an
      impact for the specific affected component, that is used instead of the overall impact. The highest
      impact from all of the CVEs is returned as a task result.
  params:
    - name: releaseNotesImages
      type: string
      description: Base64 string of gzipped JSON array of image specific details for the advisory
    - name: internalRequestPipelineRunName
      type: string
      description: name of the PipelineRun that called this task
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: result
      description: Success if the task succeeds, the error otherwise
    - name: severity
      description: The advisory severity level
    - name: internalRequestPipelineRunName
      description: Name of the PipelineRun that called this task
    - name: internalRequestTaskRunName
      description: Name of this Task Run to be made available to caller
  volumes:
    - name: osidb-service-account-vol
      secret:
        secretName: osidb-service-account
        defaultMode: 0444
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    securityContext:
      runAsUser: 1001
  steps:
    - name: get-advisory-severity
      image: quay.io/konflux-ci/release-service-utils@sha256:e08d3a8dc0f29ef6e46b1c401662ff99e2efa2ff48694974e1e5709612a8b0da
      computeResources:
        limits:
          memory: 256Mi
        requests:
          memory: 256Mi
          cpu: '1'  # 1 is the max allowed by at least the staging cluster
      volumeMounts:
        - name: osidb-service-account-vol
          mountPath: /mnt/osidb-service-account
      env:
        - name: IMAGES_ENCODED
          value: $(params.releaseNotesImages)
        - name: RESULT_RESULT
          value: $(results.result.path)
        - name: RESULT_SEVERITY
          value: $(results.severity.path)
        - name: RESULT_INTERNAL_REQUEST_PIPELINE_RUN_NAME
          value: $(results.internalRequestPipelineRunName.path)
        - name: RESULT_INTERNAL_REQUEST_TASK_RUN_NAME
          value: $(results.internalRequestTaskRunName.path)
        - name: PARAM_INTERNAL_REQUEST_PIPELINE_RUN_NAME
          value: $(params.internalRequestPipelineRunName)
        - name: PARAM_TASK_RUN_NAME
          value: $(context.taskRun.name)
      command: ["python3"]
      args:
        - -m
        - release_service_utils.tasks.internal.get_advisory_severity
