---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-internal-request
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
      Creates an InternalRequest resource to call IIB service
  params:
    - name: pipelineRunName
      type: string
      description: The name of the Parent PipelineRun of this task
    - name: binaryImage
      type: string
      description: FBC Image to be added to index image
    - name: fbcFragment
      type: string
      description: FBC fragment built by HACBS
    - name: fromIndex
      type: string
      description: Index image (catalog of catalogs) the FBC fragment will be added to    
    - name: overwriteFromIndex
      type: string
      description: Boolean indicating if the fromIndex should be overwritten
    - name: buildTags
      type: string
      description: List of additional tags the internal index image copy should be tagged with
    - name: addArches
      type: string
      description: List of arches the index image should be built for
  steps:
    - name: create-internal-request
      image: quay.io/hacbs-release/release-utils@sha256:53d4cdd2ff8d1a0c6d1781d754678b4c61e6fefa644c17bd0a4e2ca4336a3e18
      script: |
        #!/usr/bin/env sh
        PATH=/bin:/usr/bin:/usr/local/bin
        export PATH

        resourceRequest="/tmp/$$"
        cat > ${resourceRequest} <<YAML
        ---
        apiVersion: appstudio.redhat.com/v1alpha1
        kind: InternalRequest
        metadata:
          name: "ir-$(params.pipelineRunName)"
        spec:
          request: "ir-$(params.pipelineRunName)"
          params:
            binaryImage: `printf "%q" '$(params.binaryImage)'`
            fbcFragment: $(params.fbcFragment)
            fromIndex: $(params.fromIndex)
            overwriteFromIndex: "$(params.overwriteFromIndex)"
            buildTags: `printf "%q" '$(params.buildTags)'`
            addArches: `printf "%q" '$(params.addArches)'`
        YAML
        kubectl create -f ${resourceRequest}
