---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: push-snapshot-run-empty-params
spec:
  params:
    - name: tag
      value: "test"
  taskRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/task-push-snapshot:0.9
      - name: kind
        value: task
      - name: name
        value: push-snapshot
