---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: create-trusted-artifact-array
spec:
  description: >-
    This stepaction creates trusted artifacts. It does nothing if a .skip-trusted-artifacts file exists
    in root folder.
  image: quay.io/konflux-ci/build-trusted-artifacts:653578444c73afc32b3a865fee9869a09f96c1a2
  env:
    # Set HOME variable to something else than `/` to avoid 'permission denied' problems when writing files.
    - name: HOME
      value: /tekton/home
    - name: CA_FILE
      value: $(params.caCertPath)
  params:
    - name: ociStorage
      type: string
      default: "empty"
    - name: sourceDataArtifacts
      type: array
      default: []
    - name: caCertPath
      type: string
      default: "/etc/pki/tls/certs/ca-custom-bundle.crt"
      description: Path to CA certificate bundle for TLS verification with self-signed certificates
  args:
    - create
    - --store
    - $(params.ociStorage)
    - "$(params.sourceDataArtifacts[*])"
