---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: create-trusted-artifact-array
spec:
  description: >-
    This stepaction creates trusted artifacts. It does nothing if a .skip-trusted-artifacts file exists
    in root folder.
  image: quay.io/redhat-appstudio/build-trusted-artifacts:e02102ede09aa07187cba066ad547a54724e5cf4
  env:
    # Set HOME variable to something else than `/` to avoid 'permission denied' problems when writing files.
    - name: HOME
      value: /workspace/workdir/release
  params:
    - name: ociStorage
      type: string
      default: "empty"
    - name: sourceDataArtifacts
      type: array
      default: []
  args:
    - create
    - --store
    - $(params.ociStorage)
    - "$(params.sourceDataArtifacts[*])"
