---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: rh-sign-image-run-empty-params
spec:
  params:
    - name: snapshotPath
      value: ""
    - name: dataPath
      value: ""
    - name: requester
      value: ""
    - name: requestTimeout
      value: ""
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: tasks/rh-sign-image/rh-sign-image.yaml
