---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-ocp-version
  labels:
    app.kubernetes.io/version: "0.5.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to collect OCP version tag from FBC fragment using `skopeo inspect`
  params:
    - name: fbcFragment
      description: An FBC image to inspect
      type: string
  results:
    - name: stored-version
      type: string
      description: Store OCP version number from given Image
  steps:
    - name: get-ocp-version
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
       #!/usr/bin/env sh
       set -eux

        # The value to be checked
        value=$(skopeo inspect --raw docker://"$(params.fbcFragment)" \
         | jq '.annotations."org.opencontainers.image.base.name"' | cut -d: -f2 | sed 's/"//g')

        # Define the regular expression
        pattern="^v[0-9]\.[0-9]+$"

        # Check if the value matches the pattern
        if ! echo "${value}" | grep -Eq "${pattern}"; then
            echo "Invalid format or value does not exist or does not match the required pattern."
            exit 1
        fi
        echo "Valid format."
        printf "%s" "$value" | tee "$(results.stored-version.path)"
