---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prepare-validation
  labels:
    app.kubernetes.io/version: "0.7.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to extract a pull spec from a Snapshot
  params:
    - name: snapshot
      type: string
      description: The Snapshot in JSON format to apply the mapping to
  results:
    - name: snapshot
      type: string
      description: |
        The pullSpec of the first component in the passed Snapshot.
  steps:
    - name: prepare-validation
      image:
        quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/usr/bin/env bash
        set -eux

        jq -jr '.components[0].containerImage' <<< '$(params.snapshot)' \
          | tee "$(results.snapshot.path)"
