---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: collect-collectors-resources
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: Tekton task to collect the information related to collectors
  params:
    - name: previousRelease
      type: string
      description: The namespaced name of the previous Release
    - name: release
      type: string
      description: The namespaced name of the Release
    - name: releasePlan
      type: string
      description: The namespaced name of the ReleasePlan
    - name: releasePlanAdmission
      type: string
      description: The namespaced name of the ReleasePlanAdmission
    - name: subdirectory
      description: Subdirectory inside the workspace to be used
      type: string
      default: ""
  workspaces:
    - name: data
      description: Workspace to save the CR jsons to
  results:
    - name: previousRelease
      type: string
      description: The relative path in the workspace to the stored previous release json
    - name: release
      type: string
      description: The relative path in the workspace to the stored release json
    - name: releasePlan
      type: string
      description: The relative path in the workspace to the stored releasePlan json
    - name: releasePlanAdmission
      type: string
      description: The relative path in the workspace to the stored releasePlanAdmission json
    - name: resultsDir
      type: string
      description: The relative path in the workspace to the results directory
  steps:
    - name: collect-collectors-resources
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      env:
        - name: "PREVIOUS_RELEASE"
          value: '$(params.previousRelease)'
        - name: "RELEASE"
          value: '$(params.release)'
        - name: "RELEASE_PLAN"
          value: '$(params.releasePlan)'
        - name: "RELEASE_PLAN_ADMISSION"
          value: '$(params.releasePlanAdmission)'
      script: |
        #!/usr/bin/env bash
        set -exo pipefail

        RESULTS_DIR_PATH="results"
        if [ -n "$(params.subdirectory)" ]; then
          mkdir -p "$(workspaces.data.path)/$(params.subdirectory)"
          RESULTS_DIR_PATH="$(params.subdirectory)/results"
        fi

        mkdir "$(workspaces.data.path)/$RESULTS_DIR_PATH"
        echo -n "$RESULTS_DIR_PATH" > "$(results.resultsDir.path)"

        PREVIOUS_RELEASE_PATH="$(params.subdirectory)/previous_release.json"
        echo -n "$PREVIOUS_RELEASE_PATH" > "$(results.previousRelease.path)"
        get-resource "release" "${PREVIOUS_RELEASE}" | tee "$(workspaces.data.path)/$PREVIOUS_RELEASE_PATH"
        
        RELEASE_PATH="$(params.subdirectory)/release.json"
        echo -n "$RELEASE_PATH" > "$(results.release.path)"
        get-resource "release" "${RELEASE}" | tee "$(workspaces.data.path)/$RELEASE_PATH"

        RELEASE_PLAN_PATH="$(params.subdirectory)/release_plan.json"
        echo -n "$RELEASE_PLAN_PATH" > "$(results.releasePlan.path)"
        get-resource "releaseplan" "${RELEASE_PLAN}" | tee "$(workspaces.data.path)/$RELEASE_PLAN_PATH"

        RELEASE_PLAN_ADMISSION_PATH="$(params.subdirectory)/release_plan_admission.json"
        echo -n "$RELEASE_PLAN_ADMISSION_PATH" > "$(results.releasePlanAdmission.path)"
        get-resource "releaseplanadmission" "${RELEASE_PLAN_ADMISSION}" \
          | tee "$(workspaces.data.path)/$RELEASE_PLAN_ADMISSION_PATH"
