---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sign-oot-kmods
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Task to sign out-of-tree kernel modules using the internal signing server
  params:
    - name: dataPath
      type: string
      description: Path to the data JSON in the data workspace
    - name: signedKmodsPath
      type: string
      description: Path where the kernel modules are stored in the workspace
    - name: kerberosRealm
      type: string
      description: Name of the key used to sign the kernel modules
    - name: signingAuthor
      type: string
      description: Human name responsible for the signing process
    - name: checksumFingerprint
      type: string
      description: Secret containing the host key database for SSH the server running signing
    - name: checksumKeytab
      type: string
      description: Secret containing keytab file for the Kerberos user / server
    - name: signing-secret
      type: string
      description: Secret containing the fields signHost, SignKey and SignUser
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored
      type: string
      default: "empty"
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire
      type: string
      default: "1d"
    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable
      type: string
      default: ""
    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""
    - name: sourceDataArtifact
      type: string
      description: Location of trusted artifacts to be used to populate data directory
      default: ""
    - name: dataDir
      description: The location where data will be stored
      type: string
      default: /var/workdir/release
    - name: taskGitUrl
      type: string
      description: The git repository URL for task and StepAction resolution
      default: https://github.com/konflux-ci/release-service-catalog.git
    - name: taskGitRevision
      type: string
      description: The git revision for task and StepAction resolution
      default: main
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: sourceDataArtifact
      type: string
      description: Produced trusted data artifact
  volumes:
    - name: bs-keytab
      secret:
        secretName: $(params.checksumKeytab)
        defaultMode: 0444
    - name: checksum-fingerprint
      secret:
        secretName: $(params.checksumFingerprint)
        defaultMode: 0444
    - name: signing-secret-vol
      secret:
        secretName: $(params.signing-secret)
        defaultMode: 0444
    - name: workdir
      emptyDir: {}
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    securityContext:
      runAsUser: 1001
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"
  steps:
    - name: use-trusted-artifact
      computeResources:
        limits:
          memory: 64Mi
        requests:
          memory: 64Mi
          cpu: 30m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)
    - name: sign-files
      image: quay.io/lgallovi-test/release-service-utils@sha256:1e92136d6ec405d71f6172089de4ec82e7609c3eb22fd2aa6ce3973c73d2dac6
      computeResources:
        limits:
          memory: 768Mi
        requests:
          memory: 768Mi
          cpu: 300m
      volumeMounts:
        - name: checksum-fingerprint
          mountPath: "/etc/sec-checksum"
        - name: bs-keytab
          mountPath: "/etc/sec-keytab"
        - name: signing-secret-vol
          mountPath: "/etc/secrets"
      env:
        - name: PARAM_DATA_DIR
          value: $(params.dataDir)
        - name: PARAM_SIGNED_KMODS_PATH
          value: $(params.signedKmodsPath)
        - name: PARAM_KERBEROS_REALM
          value: $(params.kerberosRealm)
        - name: PARAM_SIGNING_AUTHOR
          value: $(params.signingAuthor)
        - name: TASK_RUN_UID
          value: $(context.taskRun.uid)
      command: ["python3", "-m", "release_service_utils.tasks.managed.sign_oot_kmods"]
    - name: create-trusted-artifact
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 250m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
