---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: extract-index-image-run-empty-params
spec:
  params:
    - name: inputDataFile
      value: ""
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: main
      - name: pathInRepo
        value: catalog/task/extract-index-image/0.1/extract-index-image.yaml
