---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prepare-validation
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
spec:
  description: >-
    Tekton task to extract a pull spec from an Application Snapshot
  params:
    - name: applicationSnapshot
      type: string
      description: The ApplicationSnapshot in JSON format to apply the mapping to
  results:
    - name: applicationSnapshot
      description: |
        The pullSpec of the first component in the passed AppicationSnapshot.
  steps:
    - name: prepare-validation
      image: quay.io/hacbs-release/release-utils
      script: |
        #!/usr/bin/env sh
        set -eux

        jq -jr '.components[0].containerImage' <<< '$(params.applicationSnapshot)' \
          | tee $(results.applicationSnapshot.path)
