#!/usr/bin/env bash
set -eux

echo Mock marketplacesvm_push_wrapper called with: $*
echo $* > "$(params.dataDir)/mock_wrapper.txt"
echo "$CLOUD_CREDENTIALS" > "$(params.dataDir)/mock_cloud_credentials.txt"

/home/pubtools-marketplacesvm-wrapper/marketplacesvm_push_wrapper "$@" --dry-run

# create fake artifacts which would be created by pubtools-marketplacesvm-marketplace-push
mkdir -p artifacts/20260430181240/
touch artifacts/20260430181240/pushitems.jsonl
touch artifacts/20260430181240/clouds.json
