#!/usr/bin/env bash
set -euo pipefail

_this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_new_path="${PATH}"
_new_path="${_new_path//:${_this_dir}/}"
_new_path="${_new_path/#${_this_dir}:/}"

for arg in "$@"; do
    if [[ "${arg}" == staged:* ]]; then
        staged_dir="${arg#staged:}"
        find "${staged_dir}" -type f -o -type d | sort > "$(params.dataDir)/mock_staged_dir.txt"
        break
    fi
done

PATH="${_new_path}" command pushsource-ls "$@" 2>&1 | tee "$(params.dataDir)/mock_pushsource_ls.txt"
exit "${PIPESTATUS[0]}"
