---
apiVersion: tekton.dev/v1beta1
kind: StepAction
metadata:
  name: use-trusted-artifact
spec:
  description: >-
    This stepaction extracts a Trusted Artifact into a folder.
  image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:15d7dc86012e41b10d1eb37679ec03ee75c96436224fadd0938a49dc537aa4ad
  env:
    # Set HOME variable to something else than `/` to avoid 'permission denied' problems when writing files.
    - name: HOME
      value: /tekton/home
    - name: ORAS_OPTIONS
      value: $(params.orasOptions)
    - name: CA_FILE
      value: $(params.caCertPath)
  params:
    - name: workDir
      type: string
    - name: sourceDataArtifact
      type: string
      default: ""
    - name: orasOptions
      type: string
      default: ""
      description: oras options to pass to Trusted Artifacts calls
    - name: caCertPath
      type: string
      default: ""
      description: Path to CA certificate bundle for TLS verification with self-signed certificates
  args:
    - use
    - $(params.sourceDataArtifact)=$(params.workDir)
