---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: skopeo-copy-run-empty-params
spec:
  params:
    - name: srcImageURL
      value: ""
    - name: destImageURL
      value: ""
    - name: srcToken
      value: ""
    - name: destToken
      value: ""
    - name: retries
      value: ""
  taskRef:
    name: skopeo-copy
    bundle: quay.io/hacbs-release/task-skopeo-copy:0.1
