---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: skopeo-copy-run-empty-params
spec:
  params:
    - name: srcImageURL
      value: ""
    - name: destImageURL
      value: ""
    - name: srcToken
      value: ""
    - name: destToken
      value: ""
    - name: retries
      value: ""
  taskRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/task-skopeo-copy:0.1
      - name: kind
        value: task
      - name: name
        value: skopeo-copy
