---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release-run-empty-params
spec:
  params:
    - name: release
      value: ""
    - name: releaseplan
      value: ""
    - name: releaseplanadmission
      value: ""
    - name: releasestrategy
      value: ""
    - name: snapshot
      value: ""
    - name: enterpriseContractPolicy
      value: ""
    - name: verify_ec_task_bundle
      value: ""
  pipelineRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: legacy
      - name: pathInRepo
        value: catalog/pipeline/deploy-release/0.6/deploy-release.yaml
