---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: ${ec_policy_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  description: "Red Hat's enterprise requirements"
  publicKey: "k8s://openshift-pipelines/public-key"
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
      policy:
        - oci::quay.io/enterprise-contract/ec-release-policy:konflux
      config:
        exclude:
          - step_image_registries
          - 'tasks.required_tasks_found:prefetch-dependencies'
          - slsa_source_correlated.source_code_reference_provided
        include:
          - '@slsa3'
