---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-pvc
  labels:
    originating-tool: "${originating_tool}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
