---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-release-service-account
  labels:
    originating-tool: "${originating_tool}"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-release-service-account-binding
  labels:
    originating-tool: "${originating_tool}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-release-service-account
subjects:
  - kind: ServiceAccount
    name: ${managed_sa_name}
    namespace: ${managed_namespace}
