---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  data:
    mapping:
      components:
        - name: ${component_name}
          repository: ${released_image_push_repo}
      defaults:
        tags:
          - latest
        pushSourceContainer: false
        public: true
      registrySecret: quay-api-token
    tpa:
      server: stage
      atlas-sso-secret-name: "atlas-staging-sso-secret-${component_name}"
      atlas-retry-aws-secret-name: "atlas-retry-s3-staging-secret-${component_name}"
    sign:
      cosignSecretName: "konflux-cosign-signing-stage-${component_name}"
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/push-to-external-registry/push-to-external-registry.yaml
      resolver: git
      ociStorage: ${ta_oci_storage}
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: ${ec_policy_name}
