---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${managed_sa_name}
  labels:
    originating-tool: "${originating_tool}"
secrets:
  - name: hacbs-release-tests-token
  - name: release-catalog-trusted-artifacts-quay-secret
imagePullSecrets:
  - name: hacbs-release-tests-token
  - name: release-catalog-trusted-artifacts-quay-secret
