#!/usr/bin/env bash
set -eu

mkdir -p "${PARAM_DATA_DIR}"
echo "$*" >> "${PARAM_DATA_DIR}/mock_kinit.txt"

if [[ "$1" == *@* && "$2" == "-k" && "$3" == "-t" && "$4" == /etc/sec-keytab/keytab-build-and-sign.keytab ]]; then
  exit 0
fi

echo "Error: Incorrect kinit call: $*" >&2
exit 1
