---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prepare-validation
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to extract a pull spec from a Snapshot.
    
    The purpose of this task is to extract just a single component's pullSpec from a passed Snapshot.
  params:
    - name: snapshot
      type: string
      description: The Snapshot in JSON format to apply the mapping to
  results:
    - name: snapshot
      type: string
      description: |
        The pullSpec of the first component in the passed Snapshot.
  steps:
    - name: prepare-validation
      image:
        quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service-utils@sha256:5386f8892eaafa3f151292eb41738b4b436e41c9f03bac482b344d8b280e819c
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 50m
      script: |
        #!/usr/bin/env bash
        set -eux

        jq -jr '.components[0].containerImage' <<< '$(params.snapshot)' \
          | tee "$(results.snapshot.path)"
