#!/usr/bin/env bash
set -eo pipefail

if [[ "$1" == "manifest" && "$2" == "fetch" ]]; then
  echo '{"mediaType": "application/vnd.oci.image.manifest.v1+json", "layers": []}'
elif [[ "$1" == "blob" && "$2" == "fetch" ]]; then
  for ((i=3; i<=$#; i++)); do
    if [[ "${!i}" == "--output" ]]; then
      j=$((i + 1))
      touch "${!j}"
      break
    fi
  done
elif [[ "$1" == "pull" ]]; then
  exit 1
elif [[ "$1" == "resolve" ]]; then
  echo "sha256:resolved123"
fi
