#!/usr/bin/env bash
set -eo pipefail

if [[ "$*" == *"--raw"* ]]; then
  echo '{"mediaType": "application/vnd.oci.image.manifest.v1+json"}'
else
  echo '{"Architecture": "amd64", "Os": "linux", "Digest": "sha256:abcdef1234"}'
fi
