---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-internal-requests
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to delete internal requests associated with a pipelinerun
  params:
    - name: pipelineRunUid
      type: string
      description: The uid of the current pipelineRun. It is only available at the pipeline level
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  volumes:
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    securityContext:
      runAsUser: 1001
  steps:
    - name: cleanup-internal-requests
      image: quay.io/konflux-ci/release-service-utils@sha256:e08d3a8dc0f29ef6e46b1c401662ff99e2efa2ff48694974e1e5709612a8b0da
      computeResources:
        limits:
          memory: 192Mi
        requests:
          memory: 192Mi
          cpu: 200m
      command: ["/home/scripts/python/tasks/managed/cleanup_internal_requests.py"]
      args: ["--pipeline-run-uid", "$(params.pipelineRunUid)"]
