---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-workspace
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to delete a given directory in a passed workspace
  params:
    - name: subdirectory
      type: string
      description: The directory to remove within the workspace
  workspaces:
    - name: input
      description: Workspace where the directory to cleanup exists
  steps:
    - name: cleanup
      image:
        quay.io/hacbs-release/release-base-image@sha256:9e7fd1a3ccf0d2c8077f565c78e50862a7cc4792d548b5c01c8b09077e6d23a7
      script: |
        #!/usr/bin/env sh
        set -eux

        if [ -z "$(params.subdirectory)" ] ; then
            echo "The empty string is not a valid subdirectory"
            exit 0
        fi

        CLEANUP_DIR="$(workspaces.input.path)/$(params.subdirectory)"

        if [ -d "${CLEANUP_DIR}" ] ; then
          # Delete a directory and its contents
          rm -rf "${CLEANUP_DIR}"/
        fi
