#!/usr/bin/env python3
"""Unit tests for update-infra-deployments Task Python script.

Generated by tektonit autonomous test generator.
Tests the GitHub App token generation and PR creation logic.
"""

import os
import sys
import json
import tempfile
import textwrap
from pathlib import Path
import subprocess
import pytest


@pytest.fixture
def script_env(tmp_path):
    """Create test environment with mocked data and script."""

    # Create mock data JSON
    data_json = tmp_path / "data.json"
    data_json.write_text(json.dumps({
        "targetGHRepo": "test-org/test-repo",
        "githubAppID": "12345",
        "githubAppInstallationID": "67890"
    }))

    # Create mock snapshot JSON
    snapshot_json = tmp_path / "snapshot.json"
    snapshot_json.write_text(json.dumps({
        "components": []
    }))

    # Simplified test script (key parts of the actual script)
    script_content = textwrap.dedent('''
        #!/usr/bin/env python3
        import json
        import os
        import sys

        # Read data JSON
        with open(os.environ.get('DATA_JSON_PATH'), 'r') as f:
            data = json.load(f)
            target_gh_repo = data.get(
                'targetGHRepo',
                os.environ.get('DEFAULT_TARGET_GH_REPO')
            )
            github_app_id = str(data.get(
                'githubAppID',
                os.environ.get('DEFAULT_GITHUB_APP_ID')
            ))
            github_app_installation_id = str(data.get(
                'githubAppInstallationID',
                os.environ.get('DEFAULT_GITHUB_APP_INSTALLATION_ID')
            ))

        # Validate required fields
        if not target_gh_repo:
            print("Error: targetGHRepo not provided", file=sys.stderr)
            sys.exit(1)

        if not github_app_id:
            print("Error: githubAppID not provided", file=sys.stderr)
            sys.exit(1)

        # Success - print the config
        print(f"Target repo: {target_gh_repo}")
        print(f"App ID: {github_app_id}")
        print(f"Installation ID: {github_app_installation_id}")
        sys.exit(0)
    ''')

    script_file = tmp_path / "script.py"
    script_file.write_text(script_content)

    env = os.environ.copy()
    env["DATA_JSON_PATH"] = str(data_json)
    env["SNAPSHOT_PATH"] = str(snapshot_json)
    env["DEFAULT_TARGET_GH_REPO"] = "default-org/default-repo"
    env["DEFAULT_GITHUB_APP_ID"] = "99999"
    env["DEFAULT_GITHUB_APP_INSTALLATION_ID"] = "88888"

    return script_file, env, tmp_path


def run_script(script_file, env):
    """Run the Python script and return results."""
    result = subprocess.run(
        [sys.executable, str(script_file)],
        capture_output=True,
        text=True,
        env=env,
        timeout=30
    )
    return result.returncode, result.stdout, result.stderr


# ── Suite: Happy Path ──────────────────────────────────

class TestHappyPath:
    """Test successful execution paths."""

    def test_success_with_all_fields_from_data_json(self, script_env):
        """Verify script reads targetGHRepo, githubAppID, and githubAppInstallationID from data.json."""
        script_file, env, tmp_path = script_env

        returncode, stdout, stderr = run_script(script_file, env)

        assert returncode == 0, f"Script should succeed, got stderr: {stderr}"
        assert "Target repo: test-org/test-repo" in stdout
        assert "App ID: 12345" in stdout
        assert "Installation ID: 67890" in stdout

    def test_success_with_defaults_when_fields_missing(self, script_env):
        """Verify script uses defaults when fields are missing from data.json."""
        script_file, env, tmp_path = script_env

        # Create data.json without the optional fields
        data_json = tmp_path / "data.json"
        data_json.write_text(json.dumps({}))

        returncode, stdout, stderr = run_script(script_file, env)

        assert returncode == 0
        assert "Target repo: default-org/default-repo" in stdout
        assert "App ID: 99999" in stdout
        assert "Installation ID: 88888" in stdout


# ── Suite: Error Handling ──────────────────────────────

class TestErrorPaths:
    """Test error handling and validation."""

    def test_error_when_data_json_missing(self, script_env):
        """Verify script fails when DATA_JSON_PATH file doesn't exist."""
        script_file, env, tmp_path = script_env

        # Point to non-existent file
        env["DATA_JSON_PATH"] = str(tmp_path / "nonexistent.json")

        returncode, stdout, stderr = run_script(script_file, env)

        assert returncode != 0, "Script should fail with missing data file"

    def test_error_when_data_json_invalid(self, script_env):
        """Verify script fails with invalid JSON."""
        script_file, env, tmp_path = script_env

        # Write invalid JSON
        data_json = tmp_path / "data.json"
        data_json.write_text("not valid json{")

        returncode, stdout, stderr = run_script(script_file, env)

        assert returncode != 0, "Script should fail with invalid JSON"

    def test_error_when_no_target_repo_provided(self, script_env):
        """Verify script fails when targetGHRepo is not in data and no default."""
        script_file, env, tmp_path = script_env

        # Empty data and no default
        data_json = tmp_path / "data.json"
        data_json.write_text(json.dumps({}))
        del env["DEFAULT_TARGET_GH_REPO"]

        returncode, stdout, stderr = run_script(script_file, env)

        assert returncode == 1
        assert "Error: targetGHRepo not provided" in stderr


# ── Suite: Edge Cases ──────────────────────────────────

class TestEdgeCases:
    """Test boundary conditions and unusual inputs."""

    def test_handles_empty_installation_id(self, script_env):
        """Verify script handles empty githubAppInstallationID."""
        script_file, env, tmp_path = script_env

        # Data with empty installation ID
        data_json = tmp_path / "data.json"
        data_json.write_text(json.dumps({
            "targetGHRepo": "test-org/test-repo",
            "githubAppID": "12345",
            "githubAppInstallationID": ""
        }))

        returncode, stdout, stderr = run_script(script_file, env)

        # Should use default
        assert returncode == 0
        assert "Installation ID: " in stdout

    def test_handles_numeric_ids_as_strings(self, script_env):
        """Verify script converts numeric IDs to strings."""
        script_file, env, tmp_path = script_env

        # Data with numeric IDs (not strings)
        data_json = tmp_path / "data.json"
        data_json.write_text(json.dumps({
            "targetGHRepo": "test-org/test-repo",
            "githubAppID": 12345,  # numeric, not string
            "githubAppInstallationID": 67890
        }))

        returncode, stdout, stderr = run_script(script_file, env)

        assert returncode == 0
        assert "App ID: 12345" in stdout


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
