---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${managed_namespace}

resources:
  - ../../../shared/resources/managed
  - sa.yaml
  - sa-rolebinding.yaml
  - rpa.yaml
  - secrets/managed-secrets.yaml
