---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bundle-fbc-release-pipelinerun
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton release pipeline to interact with FBC Pipeline
  params:
    - name: snapshot
      type: string
      description: The Snapshot in JSON format
    - name: enterpriseContractPolicy
      type: string
      description: JSON representation of the EnterpriseContractPolicy
    - name: fbcFragment
      type: string
      description: FBC fragment built by HACBS
    - name: fromIndex
      type: string
      description: Index image (catalog of catalogs) the FBC fragment will be added to
    - name: overwriteFromIndex
      type: string
      description: Boolean indicating if the fromIndex should be overwritten
    - name: binaryImage
      type: string
      description: OCP binary image to be baked into the index image
    - name: buildTags
      type: string
      description: List of additional tags the internal index image copy should be tagged with
    - name: addArches
      type: string
      description: List arches to be added to be built
  workspaces:
    - name: release-workspace
  tasks:
    - name: verify-enterprise-contract
      taskRef:
        name: verify-enterprise-contract-v2
        bundle: quay.io/hacbs-release/verify-enterprise-contract-v2:main
      params:
        - name: IMAGES
          value: $(params.snapshot)
        - name: SSL_CERT_DIR
          value: /var/run/secrets/kubernetes.io/serviceaccount
        - name: POLICY_CONFIGURATION
          value: $(params.enterpriseContractPolicy)
        - name: STRICT
          value: "0"
    - name: create-internal-request
      taskRef:
        name: create-internal-request
        bundle: quay.io/hacbs-release/task-create-internal-request:0.1
      params:
        - name: pipelineRunName
          value: $(context.pipelineRun.name)
        - name: fbcFragment
          value: $(params.fbcFragment)
        - name: fromIndex
          value: $(params.fromIndex)
        - name: overwriteFromIndex
          value: $(params.overwriteFromIndex)
        - name: binaryImage
          value: $(params.binaryImage)
        - name: buildTags
          value: $(params.buildTags)
        - name: addArches
          value: $(params.addArches)
