apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: echo
spec:
  params:
  - description: Text to echo
    name: text
    type: string
  steps:
  - args:
    - $(params.text)
    command:
    - echo
    image: alpine
    name: echo
    resources: {}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: hello-world
spec:
  tasks:
  - name: echo-hello-world
    params:
    - name: text
      value: Hello, World!
    taskRef:
      bundle: quay.io/hacbs-release/hello-world:0.3-alpine
      name: echo
