---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "release"
  name: update-infra-deployments
spec:
  description: |-
    * This task clones a GitHub repository specified in the 'targetGHRepo' key of the input data file.
    * If 'targetGHRepo' is not provided, it defaults to 'defaultTargetGHRepo: redhat-appstudio/infra-deployments'.
    * It then runs a script obtained from the 'infra-deployment-update-script' key in the data file,
      which can modify text files.
    * Finally, it generates a pull request for the specified repository using the modified files.
  params:
    - name: dataJsonPath
      description: path to data json file
      type: string
    - name: snapshotPath
      type: string
      description: path to snapshot json file
    - name: defaultTargetGHRepo
      type: string
      description: GitHub repository of the infra-deployments code
      default: redhat-appstudio/infra-deployments
    - name: defaultGithubAppID
      type: string
      description: Default ID of Github app used for updating PR
      default: "305606"
    - name: defaultGithubAppInstallationID
      type: string
      description: Default Installation ID of Github app in the organization
      default: "35269675"
    - name: sharedSecret
      type: string
      description: secret in the namespace which contains private key for the GitHub App
      default: infra-deployments-pr-creator
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored
      type: string
      default: "empty"
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire
      type: string
      default: "1d"
    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable
      type: string
      default: ""
    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""
    - name: sourceDataArtifact
      type: string
      description: Location of trusted artifacts to be used to populate data directory
      default: ""
    - name: dataDir
      description: The location where data will be stored
      type: string
      default: /var/workdir/release
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks and stepactions to be used are stored
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: sourceDataArtifact
      type: string
      description: Produced trusted data artifact
  volumes:
    - name: infra-deployments-pr-creator
      secret:
        # 'private-key' - private key for Github app
        secretName: $(params.sharedSecret)
    - name: workdir
      emptyDir: {}
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    securityContext:
      runAsUser: 1001
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"
  steps:
    - name: use-trusted-artifact
      computeResources:
        limits:
          memory: 32Mi
        requests:
          memory: 32Mi
          cpu: 20m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)
    - name: update-infra-deployments
      image: quay.io/konflux-ci/release-service-utils@sha256:e08d3a8dc0f29ef6e46b1c401662ff99e2efa2ff48694974e1e5709612a8b0da
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 350m
      volumeMounts:
        - name: infra-deployments-pr-creator
          mountPath: /secrets/deploy-key
      env:
        - name: PARAM_WORK_DIR
          value: /var/workdir
        - name: PARAM_DATA_DIR
          value: $(params.dataDir)
        - name: PARAM_DATA_JSON_PATH
          value: $(params.dataJsonPath)
        - name: PARAM_SNAPSHOT_PATH
          value: $(params.snapshotPath)
        - name: PARAM_DEFAULT_TARGET_GH_REPO
          value: $(params.defaultTargetGHRepo)
        - name: PARAM_DEFAULT_GITHUB_APP_ID
          value: $(params.defaultGithubAppID)
        - name: PARAM_DEFAULT_GITHUB_APP_INSTALLATION_ID
          value: $(params.defaultGithubAppInstallationID)
        - name: GITHUB_API_URL
          value: https://api.github.com
        - name: GITHUBAPP_KEY_PATH
          value: /secrets/deploy-key/private-key
      command: ["/home/scripts/python/tasks/managed/update_infra_deployments.py"]
    - name: create-trusted-artifact
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 250m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
