---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skopeo-copy-task
spec:
  params:
    - name: srcImageURL
      description: Source URL
      type: string
    - name: destImageURL
      description: Destination URL
      type: string
    - name: srcToken
      description: Robot bearer token for source
      type: string
    - name: destToken
      description: Robot bearer token for destination
      type: string
    - name: retries
      description: Retry skopeo copy N times.
      type: string
      default: "0"
  steps:
    - name: skopeo-copy
      image: quay.io/skopeo/stable:v1.7.0
      script: |
        if [[ -z "$(params.srcImageURL)" && -z "$(params.destImageURL)" ]]
        then
          exit 1 # Missing URL parameters
        elif [[ -z "$(params.srcToken)" && -z "$(params.destToken)" ]]
        then
          exit 2 # Missing TOKEN parameters
        fi
        srcDigest=$(skopeo inspect --format '{{.Digest}}' "$(params.srcImageURL)" 2>/dev/null)
        destDigest=$(skopeo inspect --format '{{.Digest}}' "$(params.destImageURL)" 2>/dev/null)
        if [[ "$destDigest" != "$srcDigest" || -z "$destDigest" ]]
        then
          skopeo copy \
            --all \
            --preserve-digests \
            --retry-times "$(params.retries)" \
            --src-registry-token  "$(params.srcToken)" \
            --dest-registry-token "$(params.destToken)" \
            "$(params.srcImageURL)" \
            "$(params.destImageURL)" ;
        fi
