---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-ocp-tag
  labels:
    app.kubernetes.io/version: "0.2.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to update pull-spec tag with
    valid OCP version from get-ocp-version task.
  params:
    - name: fromIndex
      description: The source Index image (catalog of catalogs) FBC fragment
      type: string
    - name: targetIndex
      description: Index image (catalog of catalogs) the FBC fragment will be added to
      type: string
    - name: binaryImage
      description: OCP binary image to be baked into the index image
      type: string
    - name: ocpVersion
      description: OCP version tag to replace the current set tags on index images
      type: string
  results:
    - name: updated-fromIndex
      type: string
      description: source Index image (catalog of catalogs) FBC fragment with updated tag
    - name: updated-targetIndex
      type: string
      description: Index image (catalog of catalogs) the FBC fragment will be added to with updated tag
    - name: updated-binaryImage
      type: string
      description: OCP binary image to be baked into the index image with updated tag
  steps:
    - name: update-ocp-tag
      image: quay.io/hacbs-release/release-utils:4d8649dbb2b626f5fe9f4ff83c1bc3be268fad31
      script: |
       #!/usr/bin/env sh
       set -eu

        # Function to replace tag in an image
        replace_tag() {
            local updatedImage="${1%:*}:$(params.ocpVersion)"
            echo "$updatedImage"
        }

        # Access the updated image
        updatedFromIndex=$(replace_tag "$(params.fromIndex)")
        updatedTargetIndex=$(replace_tag "$(params.targetIndex)")
        updatedBinaryImage=$(replace_tag "$(params.binaryImage)")

        echo "Updated values"
        echo -n "$updatedFromIndex" | tee $(results.updated-fromIndex.path)
        echo
        echo -n "$updatedTargetIndex" | tee $(results.updated-targetIndex.path)
        echo
        echo -n "$updatedBinaryImage" | tee $(results.updated-binaryImage.path)
        echo