---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant_namespace}

# Collectors: custom component (multi-platform), custom SA naming, custom RP (Jira)
resources:
  - ../../../shared/resources/tenant/application.yaml
  - component.yaml
  - sa.yaml
  - sa-rolebinding.yaml
  - rp.yaml
  - secrets/tenant-secrets.yaml
