---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: blob-signing-pipeline
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton pipeline for signing base64 blobs
  params:
    - name: pipeline_image
      description: An image with CLI tools needed for the signing
      default: "quay.io/konflux-ci/release-service-utils:9d57cd95e60f0c61a118fe9261f5941815d33469"
      type: string
    - name: blob
      description: Blob that needs to be signed
      type: string
    - name: requester
      description: Name of the user that requested the signing, for auditing purposes
      type: string
    - name: config_map_name
      description: A config map name with configuration
      default: hacbs-signing-pipeline-config
      type: string
    - name: taskGitUrl
      description: The url to the git repo where the release-service-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/release-service-catalog.git
      type: string
    - name: taskGitRevision
      description: The revision in the taskGitUrl repo to be used
      type: string
  workspaces:
    - name: pipeline
  results:
    - name: signed_payload
      value: "$(tasks.request-signature.results.signed_payload)"
  tasks:
    - name: collect-blob-signing-params
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/collect-blob-signing-params/collect-blob-signing-params.yaml
      params:
        - name: config_map_name
          value: $(params.config_map_name)
    - name: request-signature
      retries: 5
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/request-blob-signature/request-blob-signature.yaml
      params:
        - name: pipeline_image
          value: "$(params.pipeline_image)"
        - name: blob
          value: "$(params.blob)"
        - name: requester
          value: $(params.requester)
        - name: sig_key_names
          value: $(tasks.collect-blob-signing-params.results.sig_key_names)
        - name: umb_ssl_cert_secret_name
          value: $(tasks.collect-blob-signing-params.results.umb_ssl_cert_secret_name)
        - name: umb_client_name
          value: $(tasks.collect-blob-signing-params.results.umb_client_name)
        - name: umb_listen_topic
          value: $(tasks.collect-blob-signing-params.results.umb_listen_topic)
        - name: umb_publish_topic
          value: $(tasks.collect-blob-signing-params.results.umb_publish_topic)
        - name: umb_url
          value: $(tasks.collect-blob-signing-params.results.umb_url)
      workspaces:
        - name: data
          workspace: pipeline
          subPath: signing
      runAfter:
        - collect-blob-signing-params
