---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release-run-empty-params
spec:
  params:
    - name: snapshot
      value: ""
    - name: enterpriseContractPolicy
      value: ""
    - name: extraConfigGitUrl
      value: ""
    - name: extraConfigGitRevision
      value: ""
    - name: extraConfigPath
      value: ""
    - name: postCleanUp
      value: ""
  pipelineRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/pipeline-release:0.13
      - name: kind
        value: pipeline
      - name: name
        value: release
