---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: push-to-external-registry-run-empty-params
spec:
  params:
    - name: release
      value: ""
    - name: releaseplan
      value: ""
    - name: releaseplanadmission
      value: ""
    - name: snapshot
      value: ""
    - name: enterpriseContractPolicy
      value: ""
    - name: postCleanUp
      value: ""
    - name: verify_ec_task_bundle
      value: ""
  pipelineRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: development
      - name: pathInRepo
        value: pipelines/push-to-external-registry/push-to-external-registry.yaml
