---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-fbc-catalog-task
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to submit a IIB build request to add/update fbc-fragments to an index image
  params:
    - name: fbcFragments
      type: string
      description: FBC fragments built by Konflux as JSON array (e.g. ["fragment1", "fragment2"])
    - name: fromIndex
      type: string
      description: >-
        Index image (catalog of catalogs) the FBC fragment will be added to
    - name: buildTags
      type: string
      description: >-
        List of additional tags the internal index image copy should be
        tagged with
    - name: addArches
      type: string
      description: List of arches the index image should be built for
    - name: buildTimeoutSeconds
      type: string
      default: "3600"
      description: Timeout seconds to receive the build state
    - name: iibServiceAccountSecret
      type: string
      description: Secret with IIB credentials to be used
    - name: publishingCredentials
      type: string
      description: Secret containing the publishing credentials used to fetch the image config
    - name: mustPublishIndexImage
      type: string
      default: "false"
      description: Whether the index image should be published (pre-determined by prepare-fbc-parameters)
    - name: mustOverwriteFromIndexImage
      type: string
      default: "false"
      description: Whether to overwrite the from index image (pre-determined by prepare-fbc-parameters)
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: jsonBuildInfo
      description: JSON build information for the requested build
    - name: buildState
      description: IIB Service build state
    - name: indexImageDigests
      description: The digests for each arch for the manifest list of the index image
    - name: iibLog
      description: The link to the log from the IIB request
    - name: exitCode
      description: The exit code from the task
  volumes:
    - name: service-account-secret
      secret:
        secretName: $(params.iibServiceAccountSecret)
        defaultMode: 0444
    - name: iib-services-config-vol
      secret:
        secretName: iib-services-config
        defaultMode: 0444
    - name: iib-overwrite-fromimage-credentials-vol
      secret:
        secretName: iib-overwrite-fromimage-credentials
        defaultMode: 0444
    - name: publishing-credentials-vol
      secret:
        optional: true
        secretName: $(params.publishingCredentials)
        defaultMode: 0444
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true

  steps:
    - name: update-fbc-catalog
      image: >-
        quay.io/konflux-ci/release-service-utils@sha256:2ae61d5886887b230860934bfc7719453e44bc8882fab5ad84a483a720c5763d
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: "1"
      volumeMounts:
        - name: service-account-secret
          mountPath: /mnt/service-account-secret
        - name: iib-services-config-vol
          mountPath: /mnt/iib-services-config
        - name: iib-overwrite-fromimage-credentials-vol
          mountPath: /mnt/iib-overwrite-fromimage-credentials
        - name: publishing-credentials-vol
          mountPath: /mnt/publishing-credentials
      env:
        - name: RESULT_JSON_BUILD_INFO
          value: $(results.jsonBuildInfo.path)
        - name: RESULT_BUILD_STATE
          value: $(results.buildState.path)
        - name: RESULT_INDEX_IMAGE_DIGESTS
          value: $(results.indexImageDigests.path)
        - name: RESULT_IIB_LOG
          value: $(results.iibLog.path)
        - name: RESULT_EXIT_CODE
          value: $(results.exitCode.path)
      command: ["python3"]
      args:
        - "-u"
        - "/home/scripts/python/tasks/internal/update_fbc_catalog.py"
        - "--fbc-fragments"
        - "$(params.fbcFragments)"
        - "--from-index"
        - "$(params.fromIndex)"
        - "--build-tags"
        - "$(params.buildTags)"
        - "--add-arches"
        - "$(params.addArches)"
        - "--must-publish-index-image"
        - "$(params.mustPublishIndexImage)"
        - "--must-overwrite-from-index-image"
        - "$(params.mustOverwriteFromIndexImage)"
        - "--build-timeout-seconds"
        - "$(params.buildTimeoutSeconds)"
