---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    git-provider: github
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
    build.appstudio.openshift.io/pipeline: '{"name": "fbc-builder", "bundle": "latest"}'
  name: ${optin_component_1_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  application: multi-optin-${application_name}
  componentName: ${optin_component_1_name}
  secret: pipelines-as-code-secret-${optin_component_1_name}
  source:
    git:
      dockerfileUrl: catalog.Dockerfile
      revision: ${optin_component_1_branch}
      context: "v4.13"          # Same context for opt-in batching
      url: "${optin_component_1_git_url}"
