---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: push-sbom-to-pyxis-run-empty-params
spec:
  params:
    - name: imageURL
      value: ""
  taskRef:
    name: push-sbom-to-pyxis
    bundle: quay.io/hacbs-release/task-push-sbom-to-pyxis:0.1
