#!/usr/bin/env bash
set -euo pipefail
echo Mock developer_portal_wrapper called with: "$@"

if ! /home/developer-portal-wrapper/developer_portal_wrapper "$@" --dry-run; then
  echo Unexpected call to developer_portal_wrapper
  exit 1
fi
