#!/usr/bin/env bash
echo Mock developer_portal_wrapper called with: "$@"

/home/developer-portal-wrapper/developer_portal_wrapper "$@" --dry-run

if ! [[ "$?" -eq 0 ]]; then
  echo Unexpected call to developer_portal_wrapper
  exit 1
fi
