---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: collect-signing-params
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to collect Konflux configuration parameters related to
    keyless signing using cosign. The task attempts to read the "cluster-config"
    ConfigMap in the "konflux-info" namespace to extract signing parameters.

    In case the ConfigMap is not found, the task will output empty strings for all parameters,
    allowing the pipeline to continue without signing parameters.
  params:
    - name: configMapName
      type: string
      description: The name of the ConfigMap to read signing parameters from
      default: cluster-config
    - name: configMapNamespace
      type: string
      description: The namespace where the ConfigMap is located
      default: konflux-info
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: enableKeylessSigning
      type: string
      description: |
        A flag indicating whether keyless signing should be enabled, based on the presence of signing parameters.
    - name: defaultOIDCIssuer
      type: string
      description: |
        A default OIDC issuer URL to be used for signing.
    - name: rekorExternalUrl
      type: string
      description: |
        The external URL of the Rekor transparency log.
    - name: rekorUrl
      type: string
      description: |
        The internal URL of the Rekor transparency log.
    - name: fulcioExternalUrl
      type: string
      description: |
        The external URL of the Fulcio certificate authority.
    - name: fulcioUrl
      type: string
      description: |
        The URL of the Fulcio certificate authority.
    - name: tufExternalUrl
      type: string
      description: |
        The external URL of the TUF repository.
    - name: tufUrl
      type: string
      description: |
        The URL of the TUF repository.
    - name: buildIdentityRegexp
      type: string
      description: |
        A regular expression to extract build identity from the OIDC token claims, if applicable.
    - name: tektonChainsIdentity
      type: string
      description: |
        The identity used in the certificate, generated by fulcio.

  volumes:
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    securityContext:
      runAsUser: 1001
  steps:
    - name: collect-signing-params
      image:
        quay.io/konflux-ci/release-service-utils@sha256:d07d51d9e04ac34fd05906ce933f82273e049e2151b26ba8b30ebde8a48974a8
      computeResources:
        limits:
          memory: 256Mi
          cpu: 100m
        requests:
          memory: 256Mi
          cpu: 100m
      env:
        - name: RESULT_ENABLE_KEYLESS_SIGNING
          value: "$(results.enableKeylessSigning.path)"
        - name: RESULT_DEFAULT_OIDC_ISSUER
          value: "$(results.defaultOIDCIssuer.path)"
        - name: RESULT_REKOR_EXTERNAL_URL
          value: "$(results.rekorExternalUrl.path)"
        - name: RESULT_REKOR_URL
          value: "$(results.rekorUrl.path)"
        - name: RESULT_FULCIO_EXTERNAL_URL
          value: "$(results.fulcioExternalUrl.path)"
        - name: RESULT_FULCIO_URL
          value: "$(results.fulcioUrl.path)"
        - name: RESULT_TUF_EXTERNAL_URL
          value: "$(results.tufExternalUrl.path)"
        - name: RESULT_TUF_URL
          value: "$(results.tufUrl.path)"
        - name: RESULT_BUILD_IDENTITY_REGEXP
          value: "$(results.buildIdentityRegexp.path)"
        - name: RESULT_TEKTON_CHAINS_IDENTITY
          value: "$(results.tektonChainsIdentity.path)"
      command:
        - src/tasks/managed/collect_signing_params.py
      args:
        - "--config-map-name"
        - "$(params.configMapName)"
        - "--config-map-namespace"
        - "$(params.configMapNamespace)"
