---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-advisory
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to create an advisory via an InternalRequest. The advisory data is pulled from the data JSON. The origin
    workspace from the ReleasePlanAdmission and Application from the Snapshot are also used. The advisory is created in
    a GitLab repository. Which repository to use is determined by the contents on the mapped repositories.
    Only all `redhat-pending` or all `redhat-prod` repositories may be specified in `.data.mapping`
  params:
    - name: releasePlanAdmissionPath
      type: string
      description: Path to the JSON string of the ReleasePlanAdmission in the data workspace
    - name: snapshotPath
      type: string
      description: Path to the JSON string of the Snapshot spec in the data workspace
    - name: dataPath
      type: string
      description: Path to the data JSON in the data workspace
    - name: environment
      type: string
      description: The environment for the advisory to be published. Options are stage and production
      default: ""
    - name: resultsDirPath
      type: string
      description: Path to the results directory in the data workspace
    - name: request
      type: string
      description: Type of request to be created
      default: "create-advisory"
    - name: synchronously
      type: string
      description: Whether the task should wait for InternalRequests to complete
      default: "true"
    - name: pipelineRunUid
      type: string
      description: The uid of the current pipelineRun. Used as a label value when creating internal requests
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored
      type: string
      default: "empty"
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire
      type: string
      default: "1d"
    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable
      type: string
      default: ""
    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""
    - name: sourceDataArtifact
      type: string
      description: Location of trusted artifacts to be used to populate data directory
      default: ""
    - name: checksum_map
      type: string
      description: >
        OCI artifact reference for checksum map from internal push-artifacts-to-cdn
        (or raw JSON for backwards compatibility)
      default: ""
    - name: dataDir
      description: The location where data will be stored
      type: string
      default: /var/workdir/release
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks and stepactions to be used are stored
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
    - name: trustedArtifactsDockerConfigSecret
      type: string
      description: The name of the secret containing dockerconfig for pulling OCI artifacts
      default: quay-token-konflux-release-trusted-artifacts-secret
  results:
    - name: advisory_url
      type: string
      description: The advisory url if one was created
    - name: advisory_internal_url
      type: string
      description: The advisory internal url if one was created
    - description: Produced trusted data artifact
      name: sourceDataArtifact
      type: string
  volumes:
    - name: workdir
      emptyDir: {}
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
    - name: trusted-artifacts-dockerconfig-secret
      secret:
        optional: true
        secretName: $(params.trustedArtifactsDockerConfigSecret)
        defaultMode: 0444
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"
    securityContext:
      runAsUser: 1001
  steps:
    - name: use-trusted-artifact
      computeResources:
        limits:
          memory: 64Mi
        requests:
          memory: 64Mi
          cpu: 30m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)
    - name: create-advisory
      image: quay.io/konflux-ci/release-service-utils@sha256:e08d3a8dc0f29ef6e46b1c401662ff99e2efa2ff48694974e1e5709612a8b0da
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 650m
      volumeMounts:
        - name: trusted-artifacts-dockerconfig-secret
          mountPath: /mnt/trusted_artifacts_dockerconfig
      env:
        - name: PARAM_DATA_DIR
          value: $(params.dataDir)
        - name: PARAM_DATA_PATH
          value: $(params.dataPath)
        - name: PARAM_SNAPSHOT_PATH
          value: $(params.snapshotPath)
        - name: PARAM_RELEASE_PLAN_ADMISSION_PATH
          value: $(params.releasePlanAdmissionPath)
        - name: PARAM_RESULTS_DIR_PATH
          value: $(params.resultsDirPath)
        - name: PARAM_ENVIRONMENT
          value: $(params.environment)
        - name: PARAM_REQUEST
          value: $(params.request)
        - name: PARAM_SYNCHRONOUSLY
          value: $(params.synchronously)
        - name: PARAM_PIPELINE_RUN_UID
          value: $(params.pipelineRunUid)
        - name: PARAM_TASK_GIT_URL
          value: $(params.taskGitUrl)
        - name: PARAM_TASK_GIT_REVISION
          value: $(params.taskGitRevision)
        - name: PARAM_TASK_NAME
          value: $(context.task.name)
        - name: PARAM_CHECKSUM_MAP
          value: $(params.checksum_map)
        - name: PARAM_TA_DOCKERCONFIG_PATH
          value: /mnt/trusted_artifacts_dockerconfig/.dockerconfigjson
        - name: RESULT_ADVISORY_URL
          value: $(results.advisory_url.path)
        - name: RESULT_ADVISORY_INTERNAL_URL
          value: $(results.advisory_internal_url.path)
      command: ["python3"]
      args:
        - -m
        - release_service_utils.tasks.managed.request_advisory_creation
    - name: create-trusted-artifact
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 250m
      ref:
        resolver: "git"
        params:
          - name: url
            value: "$(params.taskGitUrl)"
          - name: revision
            value: "$(params.taskGitRevision)"
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
