---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-sbom-to-pyxis
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task that extracts sbom from a pull spec and pushes it to Pyxis.
  params:
    - name: imageURL
      description: URL of the main binary image.
      type: string
  volumes:
    - name: workdir
      emptyDir: {}
  steps:
    - name: download-sbom-for-image
      # Image taken from https://github.com/sigstore/cosign
      # and copied to Quay
      image:
        quay.io/redhat-appstudio/cosign:v1.13.1
      args:
        - download
        - sbom
        - --output-file
        - /workdir/sbom-cyclonedx.json
        - "$(params.imageURL)"
      volumeMounts:
        - mountPath: /workdir
          name: workdir
