---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-sbom-to-pyxis
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task that extracts sboms from pull specs and pushes them to Pyxis.
  params:
    - name: mappedSnapshot
      description: The mapped snapshot in JSON format
      type: string
    - name: containerImageIDs
      description: Space separated list of Pyxis image IDs
      type: string
    - name: pyxisSecret
      type: string
      description: |
        The kubernetes secret to use to authenticate to Pyxis. It needs to contain two keys: key and cert
    - name: server
      type: string
      description: The server type to use. Options are 'production' and 'stage'
      default: production
  volumes:
    - name: workdir
      emptyDir: {}
  steps:
    - name: download-sbom-files
      image:
        quay.io/hacbs-release/release-utils:5b1a1cd9fd68625cab5573ce62e0d87e6f93f341
      volumeMounts:
        - mountPath: /workdir
          name: workdir
      script: |
        #!/usr/bin/env sh
        set -eux

        IMAGEURLS=($(jq -r '.components[].repository' <<< '$(params.mappedSnapshot)'))
        IMAGEIDS=($(params.containerImageIDs))

        if [ ${#IMAGEURLS[@]} != ${#IMAGEIDS[@]} ]; then
          echo "ERROR: Lengths of imageURLs and containerImageIDs do not match"
          exit 1
        fi

        mkdir /workdir/sboms
        cd /workdir/sboms

        for i in ${!IMAGEURLS[@]}; do
          echo "Fetching sbom for image: ${IMAGEURLS[$i]}"
          cosign download sbom --output-file ${IMAGEIDS[$i]}.json ${IMAGEURLS[$i]}
        done

    - name: push-sbom-files-to-pyxis
      image:
        quay.io/hacbs-release/release-utils:5b1a1cd9fd68625cab5573ce62e0d87e6f93f341
      env:
        - name: pyxisCert
          valueFrom:
            secretKeyRef:
              name: $(params.pyxisSecret)
              key: cert
        - name: pyxisKey
          valueFrom:
            secretKeyRef:
              name: $(params.pyxisSecret)
              key: key
      volumeMounts:
        - mountPath: /workdir
          name: workdir
      script: |
        #!/usr/bin/env sh
        set -eu

        if [[ "$(params.server)" == "production" ]]
        then
          export PYXIS_GRAPHQL_API="https://graphql-pyxis.api.redhat.com/"
        elif [[ "$(params.server)" == "stage" ]]
        then
          export PYXIS_GRAPHQL_API="https://graphql-pyxis.preprod.api.redhat.com/"
        else
          echo "Invalid server parameter. Only 'production' and 'stage' are allowed."
          exit 1
        fi

        export PYXIS_CERT_PATH=/workdir/crt
        export PYXIS_KEY_PATH=/workdir/key
        echo "${pyxisCert}" > $PYXIS_CERT_PATH
        echo "${pyxisKey}" > $PYXIS_KEY_PATH

        cd /workdir/sboms

        for FILE in *.json; do
          echo Uploading sbom to Pyxis: $FILE
          upload_sbom --sbom-path $FILE
        done
