---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: collect-extra-data
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to collect extra data from release resources
  params:
    - name: release
      type: string
      description: The namespaced name of the Release
    - name: releasePlan
      type: string
      description: The namespaced name of the ReleasePlan
    - name: releasePlanAdmission
      type: string
      description: The namespaced name of the ReleasePlanAdmission
  results:
    - name: extraData
      description: |
        Result of merging the `extraData` field of all the release resources
  steps:
    - name: collect-extra-data
      image: quay.io/hacbs-release/release-utils:f486f350df43974706fc484a13bfeefc2c8fa95a
      env:
        - name: "RELEASE"
          value: '$(params.release)'
        - name: "RELEASE_PLAN"
          value: '$(params.releasePlan)'
        - name: "RELEASE_PLAN_ADMISSION"
          value: '$(params.releasePlanAdmission)'
      script: |
        #!/usr/bin/env sh

        if ! release_result=$(get-resource "release" "${RELEASE}" "{.spec.extraData}"); then
          exit 1
        fi

        if ! release_plan_result=$(get-resource "releaseplan" "${RELEASE_PLAN}" "{.spec.extraData}"); then
          exit 1
        fi

        if ! release_plan_admission_result=$(get-resource "releaseplanadmission" "${RELEASE_PLAN_ADMISSION}" \
            "{.spec.extraData}"); then
          exit 1
        fi

        # Merge Release and ReleasePlan keys. ReleasePlan has higher priority
        merged_output=$(merge-json "$release_result" "$release_plan_result")

        # Merge now with ReleasePlanAdmission keys. ReleasePlanAdmission has higher priority
        merged_output=$(merge-json "$release_result" "$release_plan_admission_result")

        echo "$merged_output" | tee $(results.extraData.path)
