---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: apply-mapping-run-empty-params
spec:
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: tasks/apply-mapping/apply-mapping.yaml
