---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: push-to-external-registry-run-empty-params
spec:
  params:
    - name: snapshot
      value: ""
    - name: enterpriseContractPolicy
      value: ""
    - name: extraConfigGitUrl
      value: ""
    - name: extraConfigGitRevision
      value: ""
    - name: extraConfigPath
      value: ""
    - name: pyxisServerType
      value: ""
    - name: pyxisSecret
      value: ""
    - name: tag
      value: ""
    - name: postCleanUp
      value: ""
  pipelineRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/pipeline-push-to-external-registry:0.9
      - name: kind
        value: pipeline
      - name: name
        value: push-to-external-registry
