---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-release
  labels:
    app.kubernetes.io/version: "0.9"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton pipeline to verify Snapshot prior to Deployment
  params:
    - name: release
      type: string
      description:
        The namespaced name (namespace/name) of the Release custom resource initiating this pipeline execution
    - name: releaseplan
      type: string
      description: The namespaced name (namespace/name) of the releasePlan
    - name: releaseplanadmission
      type: string
      description: The namespaced name (namespace/name) of the releasePlanAdmission
    - name: releasestrategy
      type: string
      description: The namespaced name (namespace/name) of the releaseStrategy
    - name: snapshot
      type: string
      description: The namespaced name (namespace/name) of the snapshot
    - name: enterpriseContractPolicy
      type: string
      description: JSON representation of the EnterpriseContractPolicy
    - name: enterpriseContractPublicKey
      type: string
      description: Public key to use for validation by the enterprise contract
      default: k8s://openshift-pipelines/public-key
    - name: verify_ec_task_git_url
      type: string
      description: The git repo url of the verify-enterprise-contract task
    - name: verify_ec_task_git_revision
      type: string
      description: The git repo revision the verify-enterprise-contract task
    - name: verify_ec_task_git_pathInRepo
      type: string
      description: The location of the verify-enterprise-contract task in its repo
    - name: postCleanUp
      type: string
      description: Cleans up workspace after finishing executing the pipeline
      default: "true"
  workspaces:
    - name: release-workspace
  tasks:
    - name: verify-access-to-resources
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/redhat-appstudio/release-service-bundles.git
          - name: revision
            value: main
          - name: pathInRepo
            value: catalog/task/upstream/tekton/kubernetes-actions/0.3/kubernetes-actions.yaml
      params:
        - name: image
          value: "quay.io/hacbs-release/cloud-builders-kubectl\
            @sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753"
        - name: script
          value: |
            ORIGIN_NAMESPACE=$(echo $(params.release) | cut -f1 -d/)
            TARGET_NAMESPACE=$(echo $(params.releaseplanadmission) | cut -f1 -d/)
            
            RELEASE_NAME=$(echo $(params.release) | cut -f2 -d/)
            RELEASEPLAN_NAME=$(echo $(params.releaseplan) | cut -f2 -d/)
            RELEASEPLANADMISSION_NAME=$(echo $(params.releaseplanadmission) | cut -f2 -d/)
            SNAPSHOT_NAME=$(echo $(params.snapshot) | cut -f2 -d/)
            
            CAN_I_READ_RELEASES=$(kubectl auth can-i get release/${RELEASE_NAME} -n ${ORIGIN_NAMESPACE})
            CAN_I_READ_RELEASEPLANS=$(kubectl auth can-i get releaseplan/${RELEASEPLAN_NAME} -n ${ORIGIN_NAMESPACE})
            CAN_I_READ_RELEASEPLANADMISSIONS=$(kubectl auth can-i get releaseplanadmission/${RELEASEPLANADMISSION_NAME} -n ${TARGET_NAMESPACE})
            CAN_I_READ_SNAPSHOTS=$(kubectl auth can-i get snapshot/${SNAPSHOT_NAME} -n ${ORIGIN_NAMESPACE})
            CAN_I_CREATE_INTERNALREQUESTS=$(kubectl auth can-i create internalrequest -n ${TARGET_NAMESPACE})

            echo ""
            echo "CAN_I_READ_RELEASES? ${CAN_I_READ_RELEASES}"
            echo "CAN_I_READ_RELEASEPLANS? ${CAN_I_READ_RELEASEPLANS}"
            echo "CAN_I_READ_RELEASEPLANADMISSIONS? ${CAN_I_READ_RELEASEPLANADMISSIONS}"
            echo "CAN_I_READ_SNAPSHOTS? ${CAN_I_READ_SNAPSHOTS}"
            echo ""
            echo "CAN_I_CREATE_INTERNALREQUESTS? ${CAN_I_CREATE_INTERNALREQUESTS}"
            echo ""

            if [ "${CAN_I_READ_RELEASES}" == "no" ] ||\
                [ "${CAN_I_READ_RELEASEPLANS}" == "no" ] ||\
                [ "${CAN_I_READ_RELEASEPLANADMISSIONS}" == "no" ] ||\
                [ "${CAN_I_READ_SNAPSHOTS}" == "no" ] ||\
                [ "${CAN_I_CREATE_INTERNALREQUESTS}" == "no" ] ; then
              echo "Error: Cannot read or create required Release resources!"
              echo ""
              echo "This indicates that your workspace is not correctly setup"
              echo "Please reach out to a RHTAP administrator on Slack at #rhtap-users"
              exit 1
            fi

            echo "Access to Release resources verified"
    - name: collect-data
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/redhat-appstudio/release-service-bundles.git
          - name: revision
            value: legacy
          - name: pathInRepo
            value: catalog/task/collect-data/0.4/collect-data.yaml
      params:
        - name: release
          value: $(params.release)
        - name: releaseplan
          value: $(params.releaseplan)
        - name: releaseplanadmission
          value: $(params.releaseplanadmission)
        - name: releasestrategy
          value: $(params.releasestrategy)
        - name: snapshot
          value: $(params.snapshot)
        - name: subdirectory
          value: $(context.pipelineRun.uid)
      workspaces:
        - name: data
          workspace: release-workspace
      runAfter:
        - verify-access-to-resources
    - name: verify-enterprise-contract
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.verify_ec_task_git_url)
          - name: revision
            value: $(params.verify_ec_task_git_revision)
          - name: pathInRepo
            value: $(params.verify_ec_task_git_pathInRepo)
      params:
        - name: IMAGES
          value: "$(workspaces.data.path)/$(context.pipelineRun.uid)/snapshot_spec.json"
        - name: SSL_CERT_DIR
          value: /var/run/secrets/kubernetes.io/serviceaccount
        - name: POLICY_CONFIGURATION
          value: $(params.enterpriseContractPolicy)
        - name: STRICT
          value: "1"
        - name: IGNORE_REKOR
          value: "true"
        - name: PUBLIC_KEY
          value: $(params.enterpriseContractPublicKey)
      workspaces:
        - name: data
          workspace: release-workspace
      runAfter:
        - collect-data
  finally:
    - name: cleanup
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/redhat-appstudio/release-service-bundles.git
          - name: revision
            value: legacy
          - name: pathInRepo
            value: catalog/task/cleanup-workspace/0.3/cleanup-workspace.yaml
      when:
        - input: $(params.postCleanUp)
          operator: in
          values: ["true"]
      params:
        - name: subdirectory
          value: "$(context.pipelineRun.uid)"
      workspaces:
        - name: input
          workspace: release-workspace
