---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: release-run-empty-params
spec:
  params:
    - name: release
      value: ""
    - name: releaseplan
      value: ""
    - name: releaseplanadmission
      value: ""
    - name: releasestrategy
      value: ""
    - name: snapshot
      value: ""
    - name: enterpriseContractPolicy
      value: ""
    - name: verify_ec_task_bundle
      value: ""
  pipelineRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/pipeline-deploy-release:0.4
      - name: kind
        value: pipeline
      - name: name
        value: deploy-release
