---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pulp-push-disk-images
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to push disk images with Pulp
  params:
    - name: snapshot_json
      type: string
      description: String containing a JSON representation of the snapshot spec
    - name: concurrentLimit
      type: string
      description: The maximum number of images to be pulled at once
      default: 3
    - name: exodusGwSecret
      type: string
      description: Env specific secret containing the Exodus Gateway configs
    - name: exodusGwEnv
      type: string
      description: Environment to use in the Exodus Gateway. Options are [live, pre]
    - name: pulpSecret
      type: string
      description: Env specific secret containing the rhsm-pulp credentials
    - name: udcacheSecret
      type: string
      description: Env specific secret containing the udcache credentials
    - name: cgwHostname
      type: string
      description: Env specific hostname for content gateway
    - name: cgwSecret
      type: string
      description: Env specific secret containing the content gateway credentials
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
    - name: certExpirationWarnDays
      type: string
      description: Number of days before expiration to warn about certificate expiration
      default: "7"
  results:
    - name: result
      description: Success if the task succeeds, the error otherwise
  volumes:
    - name: exodus-gw-secret
      secret:
        secretName: $(params.exodusGwSecret)
        defaultMode: 0444
    - name: pulp-secret
      secret:
        secretName: $(params.pulpSecret)
        defaultMode: 0444
    - name: udcache-secret
      secret:
        secretName: $(params.udcacheSecret)
        defaultMode: 0444
    - name: redhat-workloads-token
      secret:
        secretName: redhat-workloads-token
        defaultMode: 0444
    - name: cgw-secret
      secret:
        secretName: $(params.cgwSecret)
        defaultMode: 0444
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true

  steps:
    - name: pull-and-push-images
      image: quay.io/konflux-ci/release-service-utils@sha256:def74473ef2a7acfaa2a3cff2a806634d5b91420150c003b8d461e4198d1035f
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 450m
      volumeMounts:
        - name: exodus-gw-secret
          mountPath: /mnt/exodusGwSecret
        - name: pulp-secret
          mountPath: /mnt/pulpSecret
        - name: udcache-secret
          mountPath: /mnt/udcacheSecret
        - name: redhat-workloads-token
          mountPath: /mnt/redhat-workloads-token
        - name: cgw-secret
          mountPath: /mnt/cgwSecret
      securityContext:
        runAsUser: 1001
      env:
        - name: SNAPSHOT_JSON
          value: $(params.snapshot_json)
        - name: CERT_EXPIRATION_WARN_DAYS
          value: $(params.certExpirationWarnDays)
        - name: CONCURRENT_LIMIT
          value: $(params.concurrentLimit)
        - name: EXODUS_GW_ENV
          value: $(params.exodusGwEnv)
        - name: CGW_HOSTNAME
          value: $(params.cgwHostname)
        - name: RESULT_RESULT
          value: $(results.result.path)
      command:
        - python3
      args:
        - -u
        - /home/scripts/python/tasks/internal/pulp_push_disk_images.py
