---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-file-updates
spec:
  params:
    - name: fileUpdatePath
      value: "rpa.json"
  taskRef:
    name: run-file-updates
    bundle: quay.io/hacbs-release/run-file-updates:0.1
