---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fbc-release
  labels:
    app.kubernetes.io/version: "0.14"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton release pipeline to interact with FBC Pipeline
  params:
    - name: snapshot
      type: string
      description: The Snapshot in JSON format
    - name: enterpriseContractPolicy
      type: string
      description: JSON representation of the EnterpriseContractPolicy
    - name: release
      type: string
      description:
        The namespaced name (namespace/releaseName) of the Release custom resource initiating this pipeline execution
    - name: fromIndex
      type: string
      description: The source Index image (catalog of catalogs) FBC fragment
    - name: targetIndex
      type: string
      description: Index image (catalog of catalogs) the FBC fragment will be added to
    - name: binaryImage
      type: string
      default: ""
      description: OCP binary image to be baked into the index image
    - name: buildTags
      type: string
      default: "[]"
      description: List of additional tags the internal index image copy should be tagged with
    - name: addArches
      type: string
      default: "[]"
      description: List of arches the index image should be built for
    - name: signingConfigMapName
      type: string
      default: "hacbs-signing-pipeline-config"
      description: The ConfigMap to be used by the signing Pipeline
    - name: fbcPublishingCredentials
      type: string
      default: "fbc-publishing-credentials"
      description: Secret used to publish the built index image
    - name: requestUpdateTimeout
      type: string
      description: Max seconds to wait until the status is updated
    - name: buildTimeoutSeconds
      type: string
      description: Max seconds to wait until the build finishes
    - name: verify_ec_task_bundle
      type: string
      description: The location of the bundle containing the verify-enterprise-contract task
  workspaces:
    - name: release-workspace
  results:
    - name: requestMessage
      value: $(tasks.add-fbc-contribution-to-index-image.results.requestMessage)
    - name: requestReason
      value: $(tasks.add-fbc-contribution-to-index-image.results.requestReason)
  tasks:
    - name: verify-enterprise-contract
      taskRef:
        resolver: "bundles"
        params:
          - name: bundle
            value: $(params.verify_ec_task_bundle)
          - name: kind
            value: task
          - name: name
            value: verify-enterprise-contract
      params:
        - name: IMAGES
          value: $(params.snapshot)
        - name: SSL_CERT_DIR
          value: /var/run/secrets/kubernetes.io/serviceaccount
        - name: POLICY_CONFIGURATION
          value: $(params.enterpriseContractPolicy)
        - name: STRICT
          value: "1"
    - name: add-fbc-contribution-to-index-image
      workspaces:
        - name: input
          workspace: release-workspace
      taskRef:
        resolver: "bundles"
        params:
          - name: bundle
            value: quay.io/hacbs-release/task-create-internal-request:0.6
          - name: kind
            value: task
          - name: name
            value: create-internal-request
      params:
        - name: pipelineRunName
          value: $(context.pipelineRun.name)
        - name: request
          value: "iib"
        - name: updateGenericResult
          value: "true"
        - name: params
          value:
            - name: binaryImage
              value: "$(params.binaryImage)"
            - name: fromIndex
              value: "$(params.fromIndex)"
            - name: buildTags
              value: "$(params.buildTags)"
            - name: addArches
              value: "$(params.addArches)"
            - name: buildTimeoutSeconds
              value: "$(params.buildTimeoutSeconds)"
            - name: fbcFragment
              value: '$(params.snapshot)'
              jsonKey: ".components[0].containerImage"
      runAfter:
        - verify-enterprise-contract
    - name: extract-requester-from-release
      taskRef:
        resolver: "bundles"
        params:
          - name: bundle
            value: quay.io/hacbs-release/task-kubernetes-actions:0.2
          - name: kind
            value: task
          - name: name
            value: kubernetes-actions
      params:
        - name: image
          value: "quay.io/hacbs-release/cloud-builders-kubectl\
            @sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753"
        - name: script
          value: |
            set -x

            NAMESPACE=$(echo $(params.release) | cut -d '/' -f 1)
            NAME=$(echo $(params.release) | cut -d '/' -f 2)

            AUTHOR=$(kubectl get release ${NAME} -n ${NAMESPACE} \
            -o=jsonpath='{.status.attribution.author}' | tee $(results.output-result.path))

            if [[ ${AUTHOR} == "" ]] ; then exit 1 ; fi
    - name: sign-index-image
      workspaces:
        - name: input
          workspace: release-workspace
      taskRef:
        resolver: "bundles"
        params:
          - name: bundle
            value: quay.io/hacbs-release/task-create-internal-request:0.6
          - name: kind
            value: task
          - name: name
            value: create-internal-request
      params:
        - name: pipelineRunName
          value: $(context.pipelineRun.name)
        - name: inputDataFile
          value: $(tasks.add-fbc-contribution-to-index-image.results.requestResultsFile)
        - name: request
          value: "hacbs-signing-pipeline"
        - name: params
          value:
            - name: manifest_digest
              value: "sharedRequestFile:json:.jsonBuildInfo"
              jsonKey: ".index_image_resolved"
            - name: pipeline_image
              value: "quay.io/redhat-isv/operator-pipelines-images:released"
            - name: reference
              value: $(params.targetIndex)
            - name: requester
              value: $(tasks.extract-requester-from-release.results.output-result)
            - name: config_map_name
              value: $(params.signingConfigMapName)
      when:
        - input: "$(tasks.add-fbc-contribution-to-index-image.results.genericResult)"
          operator: in
          values: ["fbc_opt_in=true"]
    - name: publish-index-image
      workspaces:
        - name: input
          workspace: release-workspace
      taskRef:
        resolver: "bundles"
        params:
          - name: bundle
            value: quay.io/hacbs-release/task-create-internal-request:0.6
          - name: kind
            value: task
          - name: name
            value: create-internal-request
      params:
        - name: pipelineRunName
          value: $(context.pipelineRun.name)
        - name: inputDataFile
          value: $(tasks.add-fbc-contribution-to-index-image.results.requestResultsFile)
        - name: request
          value: "publish-index-image-pipeline"
        - name: params
          value:
            - name: sourceIndex
              value: "sharedRequestFile:json:.jsonBuildInfo"
              jsonKey: ".index_image_resolved"
            - name: targetIndex
              value: $(params.targetIndex)
            - name: publishingCredentials
              value: $(params.fbcPublishingCredentials)
            - name: retries
              value: "0"
      when:
        - input: "$(tasks.add-fbc-contribution-to-index-image.results.genericResult)"
          operator: in
          values: ["fbc_opt_in=true"]
      runAfter:
        - sign-index-image
  finally:
    - name: cleanup
      taskRef:
        resolver: "bundles"
        params:
          - name: bundle
            value: quay.io/hacbs-release/task-cleanup-workspace:main
          - name: kind
            value: task
          - name: name
            value: cleanup-workspace
      params:
        - name: subdirectory
          value: "internal-request"
      workspaces:
        - name: input
          workspace: release-workspace
