#!/usr/bin/env bash
set -euxo pipefail

echo Mock charon called with: "$*"
echo "$*" >> "$(params.dataDir)/mock_charon.txt"

if [ ! -f "${HOME}/.charon/charon.yaml" ]
then
  echo Error: Missing charon config file
  exit 1
fi

case "$1" in
  "upload")
    ;;
  *)
    echo Error: Unexpected call
    exit 1
    ;;
esac
