#!/usr/bin/env bash
set -euxo pipefail

echo Mock oras called with: "$*"
echo "$*" >> "$(params.dataDir)/mock_oras.txt"

if [[ "$*" == "pull --registry-config"* ]]
then
  registry="$4"
  hash=${registry##*@sha256:}
  short_hash=${hash:0:6}
  mkdir -p "/var/workdir/nrrc/${short_hash}"
  pushd "/var/workdir/nrrc/${short_hash}"
  mkdir package
  touch package/package.json
  tar -zcvf test.tgz package/
  rm -rf package
  popd
else
  echo Error: Unexpected call
  exit 1
fi
