---
apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: standard-${component_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  description: >-
    Includes rules for levels 1, 2 & 3 of SLSA v0.1.
  publicKey: "k8s://openshift-pipelines/public-key"
  sources:
    - name: Release Policies
      data:
        - github.com/release-engineering/rhtap-ec-policy//data
        # Tasks from https://github.com/konflux-ci/build-definitions/tree/main/task
        - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
        # Tasks from https://gitlab.cee.redhat.com/rhel-on-konflux/rpmbuild-pipeline/-/tree/main/task
        - oci::quay.io/enterprise-contract/rpmbuild-data-acceptable-bundles:latest
        # Tasks from https://github.com/konflux-ci/tekton-tools/tree/main/tasks
        - oci::quay.io/konflux-ci/konflux-vanguard/data-acceptable-bundles:latest
        # Tasks from https://github.com/konflux-ci/konflux-test-tasks/tree/main/task
        - oci::quay.io/konflux-ci/integration-service-catalog/data-acceptable-bundles:latest
      config:
        exclude:
          - rpm_signature.allowed
          - rpm_signature.result_format
          - rpm_signature.rule_data_provided
          - schedule.weekday_restriction
        include:
          - '@redhat_rpms'
      ruleData:
        allowed_target_branch_patterns:
          - ^push-rpms-to-pulp.*$
      policy:
        - oci::quay.io/conforma/release-policy:konflux
