---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: rhtap-service-push-run-empty-params
spec:
  params:
    - name: release
      value: ""
    - name: releaseplan
      value: ""
    - name: releaseplanadmission
      value: ""
    - name: releasestrategy
      value: ""
    - name: snapshot
      value: ""
    - name: enterpriseContractPolicy
      value: ""
    - name: extraConfigGitUrl
      value: ""
    - name: extraConfigGitRevision
      value: ""
    - name: extraConfigPath
      value: ""
    - name: pyxisServerType
      value: ""
    - name: pyxisSecret
      value: ""
    - name: tag
      value: ""
    - name: postCleanUp
      value: ""
    - name: verify_ec_task_bundle
      value: ""
  pipelineRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: main
      - name: pathInRepo
        value: catalog/pipeline/rhtap-service-push/0.1/rhtap-service-push.yaml
