---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: reduce-snapshot
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to reduce snapshot
  params:
    - name: SNAPSHOT
      type: string
      description: String representation of Snapshot spec
    - name: SINGLE_COMPONENT
      type: string
      description: Single mode component enabled
    - name: SINGLE_COMPONENT_CUSTOM_RESOURCE
      type: string
      description: Custom Resource to query for built component in Snapshot
    - name: SINGLE_COMPONENT_CUSTOM_RESOURCE_NS
      type: string
      default: ""
      description: Namespace where Custom Resource is found
    - name: SNAPSHOT_PATH
      type: string
      description: The location to place the reduced Snapshot
  workspaces:
    - name: data
      description: Workspace to save the CR jsons to
  steps:
    - name: reduce
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: SINGLE_COMPONENT
          value: $(params.SINGLE_COMPONENT)
        - name: CUSTOM_RESOURCE
          value: $(params.SINGLE_COMPONENT_CUSTOM_RESOURCE)
        - name: CUSTOM_RESOURCE_NAMESPACE
          value: $(params.SINGLE_COMPONENT_CUSTOM_RESOURCE_NS)
        - name: SNAPSHOT_PATH
          value: $(params.SNAPSHOT_PATH)
      image: quay.io/enterprise-contract/ec-cli@sha256:913c7dac3d41877b01835d2e55bcd970c6cdbf4944f8176e9e3de9548642a2b4
      command: [reduce-snapshot.sh]
      onError: continue  # progress even if the step fails
