---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${tenant_namespace}

# push-rpms-to-pulp: custom component (multi-platform)
resources:
  - ../../../shared/resources/tenant/application.yaml
  - component.yaml
  - sa-rolebinding.yaml
  - ../../../shared/resources/tenant/rp.yaml
  - secrets/tenant-secrets.yaml
