---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    # Release is created manually after both component builds complete.
    release.appstudio.openshift.io/auto-release: 'false'
    release.appstudio.openshift.io/standing-attribution: 'true'
    release.appstudio.openshift.io/releasePlanAdmission: "${release_plan_admission_name}"
    originating-tool: "${originating_tool}"
  name: ${release_plan_name}
spec:
  application: ${application_name}
  target: ${managed_namespace}
  collectors:
    items:
      - name: simple-jira
        type: single-component-simplejira
        params:
          - name: jiraProjectKey
            value: "RELEASE"
          - name: jiraServer
            value: "redhat.atlassian.net"
      - name: cve
        params: []
        type: cve
      - name: doc-render
        params:
          - name: git
            value: "https://github.com/hacbs-release-tests/e2e-base.git"
          - name: branch
            value: push-rpms-to-pulp-base
          - name: path
            value: "push-rpms-to-pulp-convertyaml-collector.yaml"
        type: convertyaml
    serviceAccountName: ${tenant_collector_sa_name}
