---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${tenant_collector_sa_name}
  labels:
    originating-tool: "${originating_tool}"
secrets:
  - name: jira-collectors-secret-${component_name}
