---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: slack-webhook-notification-run-empty-params
spec:
  params:
    - name: message
      value: ""
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: tasks/slack-webhook-notification/slack-webhook-notification.yaml
