#!/usr/bin/env bash
set -euo pipefail

case "$*" in
  *"test-fbc-component@sha256:f6e744662e342c1321deddb92469b55197002717a15f8c0b1bb2d9440aac2297"*)
    echo '{ "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "annotations": {
              "org.opencontainers.image.base.name": "registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.12"
            }
          }'
    ;;
  *)
    echo "Unexpected skopeo invocation: $*" >&2
    exit 1
    ;;
esac
