---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: ${release_plan_admission_name}
  labels:
    originating-tool: "${originating_tool}"
spec:
  applications:
    - ${application_name}
  environment: ${application_name}
  data:
    releaseNotes:
      product_name: "Red Hat build of test npm"
      product_version: "1.20"
    charon:
      release: ea 
      environment: stage
      awsSecret: charon-aws-credentials-stage-${component_name}
      packageType: npm
      config: |-
        aws_profile: ronda-stage
        aws_cf_enable: True
        ignore_patterns:
          - '\..+'
          - 'index\.htm?'
          - 'JBossEULA.*'
          - 'example-settings.xml.*'
          - 'versions.txt.*'
          - 'maven-metadata-local.xml'
          - '.*\.asc'
        targets:
          stage-npm-ea:
            - bucket: stage-npm-npmjs
              prefix: /
              registry: "npm.stage.registry.redhat.com"
    intention: staging
  origin: ${tenant_namespace}
  pipeline:
    pipelineRef:
      params:
        - name: url
          value: "${RELEASE_CATALOG_GIT_URL}"
        - name: revision
          value: "${RELEASE_CATALOG_GIT_REVISION}"
        - name: pathInRepo
          value: pipelines/managed/release-to-nrrc/release-to-nrrc.yaml
      resolver: git
    serviceAccountName: ${managed_sa_name}
    timeouts:
      pipeline: 4h0m0s
      tasks: 4h0m0s
  policy: standard-${component_name}
