---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-file-updates
spec:
  params:
    - name: fileUpdatePath
      value: "rpa.json"
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: main
      - name: pathInRepo
        value: catalog/task/run-file-updates/0.3/run-file-updates.yaml
