---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: apply-mapping-run-empty-params
spec:
  params:
    - name: snapshot
      value: ""
  taskRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/task-apply-mapping:0.4
      - name: kind
        value: task
      - name: name
        value: apply-mapping
