---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-release
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton pipeline to verify Snapshot prior to Deployment
  params:
    - name: snapshot
      type: string
      description: The Snapshot in JSON format
    - name: enterpriseContractPolicy
      type: string
      description: JSON representation of the EnterpriseContractPolicy
  tasks:
    - name: verify-enterprise-contract
      taskRef:
        name: verify-enterprise-contract
        bundle: quay.io/enterprise-contract/ec-task-bundle:snapshot
      params:
        - name: IMAGES
          value: $(params.snapshot)
        - name: SSL_CERT_DIR
          value: /var/run/secrets/kubernetes.io/serviceaccount
        - name: POLICY_CONFIGURATION
          value: $(params.enterpriseContractPolicy)
        - name: STRICT
          value: "1"
