---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-release-pipeline
spec:
  tasks:
    - name: echo
      params:
        - name: text
          value: Hello, Release.
      taskRef:
        bundle: quay.io/hacbs-release/hello-release:main
        name: echo-task
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  params:
    - description: Text to echo
      name: text
      type: string
  steps:
    - args:
        - $(params.text)
      command:
        - echo
      image: alpine
      name: echo
