---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: verify-access-to-resources
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    This Tekton task is used to verify access to various resources in the pipelines. It ensures that the necessary
    resources, such as the release, release plan, release plan admission, release service config and snapshot,
    are available and accessible. Additionally, it checks if internal requests can be created if
    `requireInternalServices` is set to `true`.
  params:
    - name: release
      description: Namespace/name of the Release
      type: string
    - name: releasePlan
      description: Namespace/name of the ReleasePlan
      type: string
    - name: releasePlanAdmission
      description: Namespace/name of the ReleasePlanAdmission
      type: string
    - name: releaseServiceConfig
      description: Namespace/name of the ReleaseServiceConfig
      type: string
    - name: snapshot
      description: Namespace/name of the Snapshot
      type: string
    - name: requireInternalServices
      description: Whether internal services are required
      type: string
      default: "false"
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  volumes:
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    securityContext:
      runAsUser: 1001
  steps:
    - name: verify-access-to-resources
      image: quay.io/konflux-ci/release-service-utils@sha256:9b67510f1797cf3ef847400d0c8d58f0d62d881bbef833cd04ba6f241083e7e4
      computeResources:
        limits:
          memory: 100Mi
        requests:
          memory: 100Mi
          cpu: 10m
      env:
        - name: PARAM_RELEASE
          value: $(params.release)
        - name: PARAM_RELEASE_PLAN
          value: $(params.releasePlan)
        - name: PARAM_RELEASE_PLAN_ADMISSION
          value: $(params.releasePlanAdmission)
        - name: PARAM_RELEASE_SERVICE_CONFIG
          value: $(params.releaseServiceConfig)
        - name: PARAM_SNAPSHOT
          value: $(params.snapshot)
        - name: PARAM_REQUIRE_INTERNAL_SERVICES
          value: $(params.requireInternalServices)
      command: ["python3", "-m", "verify_access_to_resources"]
