---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: extract-binaries-from-image
spec:
  taskRef:
    resolver: "git"
    params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-bundles.git
      - name: revision
        value: main
      - name: pathInRepo
        value: tasks/extract-binaries-from-image/extract-binaries-from-image.yaml
