---
apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: augment-component-sboms-ta
  labels:
    app.kubernetes.io/version: "0.2.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: sbom

spec:
  description: >-
    Update component-level SBOMs with release-time information, optionally
    upload them to Atlas and S3.
  params:
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
      default: "empty"

    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: "1d"

    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable.
      type: string
      default: ""

    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""

    - name: sourceDataArtifact
      type: string
      description: Location of trusted artifacts to be used to populate data directory
      default: ""

    - name: dataDir
      description: The location where data will be stored
      type: string
      default: /var/workdir/release

    - name: taskGitUrl
      type: string
      description: The url to the git repo where the trusted artifact stepactions to be used are stored

    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used for trusted artifact stepactions

    - name: snapshotSpec
      type: string
      description: Path to the mapped snapshot spec.
    
    - name: atlasSecretName
      type: string
      description: >
        The name of the K8s secret containing the 'sso_account' and 'sso_token'
        keys used for Atlas OIDC authentication.

    - name: retryAWSSecretName
      type: string
      description: >
        The name of the K8s secret containing the 'atlas-aws-access-key-id' and
        'atlas-aws-secret-access-key' keys used for AWS S3 access.
      # This default value handles k8s built-in validation of secretNames
      # in mounts or env variables. With `optional: True`, the env var or
      # volume is simply not used if the secret is not found. Secret name
      # however can never be an empty string or the pipeline validation
      # fails completely. For more context, check out Secret naming:
      # https://kubernetes.io/docs/concepts/configuration/secret/#restriction-names-data
      # and their optional parameter:
      # https://kubernetes.io/docs/concepts/configuration/secret/#restriction-secret-must-exist
      default: "secret-not-present"

    - name: retryS3Bucket
      type: string
      default: ""
      description: >
        The name of the S3 bucket used to store data for the retry mechanism.

    - name: atlasApiUrl
      type: string
      default: ""
      description: URL of the Atlas API host.

    - name: ssoTokenUrl
      description: URL of the SSO token issuer.
      default: ""
      type: string

    - name: caPath
      description: Path to the certificate authority bundle to set up TPA requests.
      default: ""
      type: string

    - name: augmentConcurrency
      description: |
        Maximum number of SBOMs that will be augmented concurrently. Higher
        limit will speed up execution for larger snapshots, but will have
        higher memory requirements.
      default: "8"
      type: string

    - name: uploadConcurrency
      description: |
        Maximum number of SBOMs that will be uploaded to Atlas concurrently.
        Higher limit will speed up execution for larger snapshots, but will
        have higher memory requirements.
      default: "8"
      type: string

    - name: resultsDirPath
      type: string
      description: Path to directory in the dataDir to store JSON task results to.

    - name: cosignSecretName
      type: string
      description: K8s secret name with a cosign signing key used for SBOM attestation.
      default: "secret-not-present"

    - name: attestationPubKey
      type: string
      description: K8s reference to a secret containing a key for verifying provenance attestations
      default: ""

    - name: releaseData
      type: string
      description: Path to the merged data file from collect-data in the dataDir.

    # Configuration parameters for keyless signing, if enabled.
    - name: defaultOIDCIssuer
      type: string
      description: A default OIDC issuer URL to be used for signing.
      default: ""
    - name: rekorExternalUrl
      type: string
      description: The external URL of the Rekor transparency log.
      default: ""
    - name: fulcioExternalUrl
      type: string
      description: The external URL of the Fulcio certificate authority.
      default: ""
    - name: tufExternalUrl
      type: string
      description: The external URL of the TUF repository.
      default: ""
    - name: buildIdentityRegexp
      type: string
      description: |
        A regular expression to extract build identity from the OIDC token claims, if applicable.
      default: ""

    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt

  results:
    - description: Produced trusted data artifact
      name: sourceDataArtifact
      type: string

  volumes:
    - name: workdir
      emptyDir: {}
    - name: oidc-token
      projected:
        sources:
          - serviceAccountToken:
              audience: sigstore
              # 30 minutes should be enough to finish this task
              expirationSeconds: 1800
              path: oidc-token
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true

  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      - name: trusted-ca
        mountPath: /etc/pki/tls/certs/custom-ca
        readOnly: true
      - name: trusted-ca
        mountPath: /etc/ssl/certs/ca-custom-bundle.crt
        subPath: ca-bundle.crt
        readOnly: true
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"

  steps:
    - name: use-trusted-artifact
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)

    - name: process-component-sboms
      image: quay.io/konflux-ci/mobster@sha256:f7a92f81d26a7bfeedb5d5ff720cc184dcf67dc68e68f6d4fd44290cdef36ad7
      env:
        - name: MOBSTER_TPA_SSO_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: $(params.atlasSecretName)
              key: sso_account
              optional: true
        - name: MOBSTER_TPA_SSO_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.atlasSecretName)
              key: sso_token
              optional: true
        - name: MOBSTER_TPA_SSO_TOKEN_URL
          value: $(params.ssoTokenUrl)
        - name: MOBSTER_TPA_CA_INFO
          value: $(params.caPath)
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: $(params.retryAWSSecretName)
              key: atlas-aws-access-key-id
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.retryAWSSecretName)
              key: atlas-aws-secret-access-key
              optional: true
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: SIGN_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.cosignSecretName)
              key: SIGN_KEY
              optional: true
        - name: COSIGN_AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: $(params.cosignSecretName)
              key: AWS_DEFAULT_REGION
              optional: true
        - name: COSIGN_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: $(params.cosignSecretName)
              key: AWS_ACCESS_KEY_ID
              optional: true
        - name: COSIGN_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.cosignSecretName)
              key: AWS_SECRET_ACCESS_KEY
              optional: true
      volumeMounts:
        - mountPath: /var/run/sigstore/cosign
          name: oidc-token

      computeResources:
        limits:
          memory: 2Gi
        requests:
          memory: 2Gi
          cpu: 350m
      script: |
        #!/usr/bin/env bash
        set -eux
        # This is a little fragile, ideally it would be just a param. It's here
        # for consistency with other tasks in release-service-catalog. The
        # script below will verify that the release_id has the correct format.
        release_id=$(dirname "$(params.snapshotSpec)")

        mobster_args=(
          --data-dir "$(params.dataDir)"
          --snapshot-spec "$(params.snapshotSpec)"
          --atlas-api-url "$(params.atlasApiUrl)"
          --release-id "$release_id"
          --augment-concurrency "$(params.augmentConcurrency)"
          --upload-concurrency "$(params.uploadConcurrency)"
          --result-dir "$(params.resultsDirPath)"
          --release-data "$(params.releaseData)"
        )
        # Params are basically Bash commands, their value
        # has to be checked with -n. Env variables should
        # be checked with -v to not leak expanded secrets
        # through xtrace. Bash conditionals ([[) have to
        # be used instead of Shell conditionals ([) to use -v
        if [[ -n "$(params.defaultOIDCIssuer)" \
          && -n "$(params.rekorExternalUrl)" \
          && -n "$(params.fulcioExternalUrl)" \
          && -n "$(params.tufExternalUrl)" \
          && -n "$(params.buildIdentityRegexp)" \
        ]]; then
          # Keyless signing is used for augmentation
          cosign initialize --root "$(params.tufExternalUrl)/root.json" \
            --mirror "$(params.tufExternalUrl)"
          mobster_args+=(
            --oidc-token /var/run/sigstore/cosign/oidc-token
            --fulcio-url "$(params.fulcioExternalUrl)"
            --oidc-issuer "$(params.defaultOIDCIssuer)"
            --oidc-identity-pattern "$(params.buildIdentityRegexp)"
            --rekor-url "$(params.rekorExternalUrl)"
          )
        elif [[ -n "$(params.attestationPubKey)" \
          && -v SIGN_KEY \
          && -v COSIGN_AWS_DEFAULT_REGION \
          && -v COSIGN_AWS_ACCESS_KEY_ID \
          && -v COSIGN_AWS_SECRET_ACCESS_KEY
        ]]; then
          # Static key signing is used for augmentation
          mobster_args+=(
            --verify-key "$(params.attestationPubKey)"
            --sign-key "$SIGN_KEY"
          )
        fi
        if [[ -n "$(params.retryS3Bucket)" ]]; then
          mobster_args+=(
            --retry-s3-bucket "$(params.retryS3Bucket)"
          )
        fi
        process_component_sboms "${mobster_args[@]}"

    - name: create-trusted-artifact
      ref:
        resolver: "git"
        params:
          - name: url
            value: "$(params.taskGitUrl)"
          - name: revision
            value: "$(params.taskGitRevision)"
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
        - name: caCertPath
          value: "/etc/pki/tls/certs/custom-ca/ca-bundle.crt"
