---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-file-updates
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to run file updates
  params:
    - name: jsonKey
      type: string
      description: The json key containing the file updates
      default: ".spec.extraData.fileUpdates[]"
    - name: fileUpdatesPath
      type: string
      description: The path to the file containing the file updates
    - name: request
      type: string
      description: Name of the request
      default: "file-updates"
    - name: synchronously
      type: string
      description: Whether to run synchronously or not
      default: "true"
  workspaces:
    - name: data
      description: Workspace where the file updates to apply are defined
  steps:
    - name: run-script
      image: quay.io/hacbs-release/release-utils:34901b1694963265ac2dcfecc2f56e15a2a8c7fe
      script: |
        #!/bin/sh
        set -ex

        # Read JSON file into a variable
        jsonData=$(cat $(workspaces.data.path)/$(params.fileUpdatesPath))

        # Extract the key from the JSON file
        fileUpdates=$(echo "${jsonData}" | jq -rc "$(params.jsonKey)")
  
        # Iterate over the extracted array and call the script
        IFS=$'\n'
        for item in ${fileUpdates}
        do
          repo=$(echo "${item}" | jq -rc ".repo")
          ref=$(echo "${item}" | jq -rc '.ref // "main"')
          paths=$(echo "${item}" | jq -rc '.paths // []')
        
          internal-request -r "$(params.request)" \
                           -p repo="${repo}" \
                           -p ref="${ref}" \
                           -p paths="${paths}" \
                           -s "$(params.synchronously)"
        done
