---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-test-role
  namespace: default
rules:
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - internalrequests
      - internalrequests/status
      - releases
      - releases/status
      - releaseplans
      - releaseplanadmissions
      - releaseserviceconfigs
      - snapshots
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineruns/status
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - patch
  - apiGroups:
      -
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-test-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-test-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
