---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-test-role
  namespace: default
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - internalrequests
  - releases
  - releaseplans
  - releaseplanadmissions
  - releasestrategies
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-test-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-test-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
