---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: push-snapshot-run-empty-params
spec:
  params:
    - name: mappedSnapshot
      value: ""
  taskRef:
    name: push-snapshot
    bundle: quay.io/hacbs-release/task-push-snapshot:0.3
