---
name: Label Check
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]
jobs:
  do-not-merge:
    if: ${{ !contains(github.event.*.labels.*.name, 'prod/approved') }}
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          echo "Pull request is missing label 'prod/approved'"
          echo "This workflow fails so that the pull request cannot be merged"
          exit 1
    if: ${{ contains(github.event.*.labels.*.name, 'prod/approved') }}
    name: Allow Merging  # Without this, the action would be skipped instead of pass
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          echo "Pull request is okay to merge"
          exit 0
