---
name: Linters
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['main']
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yamllint
        uses: frenck/action-yamllint@v1
        with:
          path: catalog/
  tknparse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v3
      - name: install tkn
        uses: ./.github/actions/install-tkn
      - name: Get changed files
        uses: tj-actions/changed-files@v35
        id: changed-files
        with:
          files: |
            catalog/*/*/*/*.yaml
      - name: Run tkn util
        run: .github/scripts/tkn_check_parse.sh
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REFNAME: ${{ github.ref_name }}
