---
name: Tekton Task Tests
on:
  pull_request:
    branches: ['main']
jobs:
  run-tekton-task-tests:
    name: Run Tekton Task tests
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Check cluster info
        run: |
          kubectl cluster-info
      - name: Install Tekton
        run: |
          kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
          sleep 1
          # Wait up to 5 minutes for all the Tekton pods to be Ready
          timeout 300 bash << EOF
          while kubectl get pods --namespace tekton-pipelines -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}' | grep False > /dev/null
          do
            sleep 1
          done
          EOF
          kubectl get pods --namespace tekton-pipelines
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install tkn
        uses: ./.github/actions/install-tkn
      - name: Get changed dirs
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          files: |
            catalog/task/*/*
          dir_names: "true"
          dir_names_max_depth: "4"
      - name: Show changed dirs
        run: |
          echo ${{ steps.changed-dirs.outputs.all_changed_files }}
      - name: Test Tekton tasks
        run: .github/scripts/test_tekton_tasks.sh
        env:
          TASK_DIRS: ${{ steps.changed-dirs.outputs.all_changed_files }}
