#!/usr/bin/env bash
set -eu

if [[ "$1" == "pull" ]]; then
    build_name=$(sed -e 's_.*\/__' -e 's_@.*__' <<< "$*")
    cat > cg_import.json <<EOF
{
    "metadata_version": 0,
    "build": {
        "name": "${build_name}",
        "version": "16.1",
        "release": "10.el10_0",
        "epoch": null
    }
}
EOF
    touch test.src.rpm
    exit 0
fi

echo "mock oras: unhandled command: $*" >&2
exit 1
